// <auto-generated />
#nullable enable
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace KyrolusSous.EndpointKit.Generator;

/// <summary>
/// AOT-compatible source generator for EndpointKit.
/// Generates:
/// - Static property accessors (eliminates reflection)
/// - Filter expression builders
/// - Order expression builders
/// - Endpoint handler registrations
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class KyrolusEndpointGenerator : IIncrementalGenerator
{
    private const string AttributeName = "KyrolusAotEndpointAttribute";
    private const string AttributeNamespace = "KyrolusSous.EndpointKit.Core";
    private const string FullAttributeName = $"{AttributeNamespace}.{AttributeName}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register the attribute itself
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("KyrolusAotEndpointAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
            ctx.AddSource("KyrolusPropertyAccessor.g.cs", SourceText.From(PropertyAccessorBaseSource, Encoding.UTF8));
            ctx.AddSource("KyrolusStaticFilterBuilder.g.cs", SourceText.From(StaticFilterBuilderBaseSource, Encoding.UTF8));
            ctx.AddSource("KyrolusStaticOrderBuilder.g.cs", SourceText.From(StaticOrderBuilderBaseSource, Encoding.UTF8));
        });

        // Find all types marked with [KyrolusAotEndpoint]
        var classesWithAttribute = context.SyntaxProvider.ForAttributeWithMetadataName(
            FullAttributeName,
            predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
            transform: static (ctx, ct) => ExtractEndpointInfo(ctx, ct)
        ).Where(static info => info is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(classesWithAttribute.Collect());

        context.RegisterSourceOutput(compilationAndClasses, Execute);
    }

    private static EndpointInfo? ExtractEndpointInfo(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        var symbol = ctx.TargetSymbol as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract)
            return null;

        var attributeData = ctx.Attributes.FirstOrDefault();
        if (attributeData is null)
            return null;

        // Extract attribute properties
        string? keyProperty = null;
        ITypeSymbol? keyType = null;
        string? softDeleteProperty = null;
        string? rowVersionProperty = null;
        string? tenantIdProperty = null;
        bool enableFiltering = true;
        bool enableOrdering = true;
        string[]? allowedFilterProperties = null;
        string[]? allowedOrderProperties = null;

        foreach (var named in attributeData.NamedArguments)
        {
            switch (named.Key)
            {
                case "KeyProperty":
                    keyProperty = named.Value.Value as string;
                    break;
                case "KeyType":
                    keyType = named.Value.Value as ITypeSymbol;
                    break;
                case "SoftDeleteProperty":
                    softDeleteProperty = named.Value.Value as string;
                    break;
                case "RowVersionProperty":
                    rowVersionProperty = named.Value.Value as string;
                    break;
                case "TenantIdProperty":
                    tenantIdProperty = named.Value.Value as string;
                    break;
                case "EnableFiltering":
                    enableFiltering = named.Value.Value is bool b && b;
                    break;
                case "EnableOrdering":
                    enableOrdering = named.Value.Value is bool b2 && b2;
                    break;
                case "AllowedFilterProperties":
                    allowedFilterProperties = ExtractStringArray(named.Value);
                    break;
                case "AllowedOrderProperties":
                    allowedOrderProperties = ExtractStringArray(named.Value);
                    break;
            }
        }

        // Also get from constructor args
        if (attributeData.ConstructorArguments.Length > 0)
        {
            var firstArg = attributeData.ConstructorArguments[0];
            if (firstArg.Value is string kp)
            {
                keyProperty = kp;
            }
        }

        // Default key property to "Id"
        keyProperty ??= "Id";

        // Try to find key type from property
        if (keyType is null)
        {
            var prop = symbol.GetMembers()
                .OfType<IPropertySymbol>()
                .FirstOrDefault(p => string.Equals(p.Name, keyProperty, StringComparison.OrdinalIgnoreCase));
            keyType = prop?.Type;
        }

        // Collect all public properties
        var properties = symbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod is not null)
            .Select(p => new PropertyInfo(
                p.Name,
                p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                p.SetMethod is not null,
                IsNullableType(p.Type),
                GetUnderlyingType(p.Type),
                IsNumericType(p.Type),
                IsStringType(p.Type),
                IsBooleanType(p.Type),
                IsDateTimeType(p.Type),
                IsGuidType(p.Type),
                IsEnumType(p.Type),
                IsCollectionType(p.Type),
                GetCollectionElementType(p.Type)))
            .ToImmutableArray();

        return new EndpointInfo(
            symbol.Name,
            symbol.ContainingNamespace.ToDisplayString(),
            symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            keyProperty,
            keyType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "int",
            softDeleteProperty,
            rowVersionProperty,
            tenantIdProperty,
            enableFiltering,
            enableOrdering,
            allowedFilterProperties?.ToImmutableArray() ?? ImmutableArray<string>.Empty,
            allowedOrderProperties?.ToImmutableArray() ?? ImmutableArray<string>.Empty,
            properties);
    }

    private static string[]? ExtractStringArray(TypedConstant constant)
    {
        if (constant.Kind == TypedConstantKind.Array && !constant.Values.IsDefaultOrEmpty)
        {
            return constant.Values
                .Where(v => v.Value is string)
                .Select(v => (string)v.Value!)
                .ToArray();
        }
        return null;
    }

    private static bool IsNullableType(ITypeSymbol type)
    {
        if (type.NullableAnnotation == NullableAnnotation.Annotated)
            return true;
        if (type is INamedTypeSymbol named && named.IsGenericType)
        {
            return named.ConstructedFrom.ToDisplayString() == "System.Nullable<T>";
        }
        return false;
    }

    private static string? GetUnderlyingType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.IsGenericType &&
            named.ConstructedFrom.ToDisplayString() == "System.Nullable<T>")
        {
            return named.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }
        return null;
    }

    private static bool IsNumericType(ITypeSymbol type)
    {
        var underlying = GetUnderlyingTypeSymbol(type) ?? type;
        return underlying.SpecialType switch
        {
            SpecialType.System_Int16 or SpecialType.System_Int32 or SpecialType.System_Int64 or
            SpecialType.System_UInt16 or SpecialType.System_UInt32 or SpecialType.System_UInt64 or
            SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_Decimal or
            SpecialType.System_Byte or SpecialType.System_SByte => true,
            _ => false
        };
    }

    private static bool IsStringType(ITypeSymbol type) =>
        (GetUnderlyingTypeSymbol(type) ?? type).SpecialType == SpecialType.System_String;

    private static bool IsBooleanType(ITypeSymbol type) =>
        (GetUnderlyingTypeSymbol(type) ?? type).SpecialType == SpecialType.System_Boolean;

    private static bool IsDateTimeType(ITypeSymbol type)
    {
        var underlying = GetUnderlyingTypeSymbol(type) ?? type;
        var name = underlying.ToDisplayString();
        return name is "System.DateTime" or "System.DateTimeOffset" or "System.DateOnly" or "System.TimeOnly";
    }

    private static bool IsGuidType(ITypeSymbol type)
    {
        var underlying = GetUnderlyingTypeSymbol(type) ?? type;
        return underlying.ToDisplayString() == "System.Guid";
    }

    private static bool IsEnumType(ITypeSymbol type)
    {
        var underlying = GetUnderlyingTypeSymbol(type) ?? type;
        return underlying.TypeKind == TypeKind.Enum;
    }

    private static bool IsCollectionType(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol named) return false;
        var interfaces = named.AllInterfaces;
        return interfaces.Any(i => i.ToDisplayString().StartsWith("System.Collections.Generic.IEnumerable<", StringComparison.Ordinal));
    }

    private static string? GetCollectionElementType(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol named) return null;
        var enumerable = named.AllInterfaces.FirstOrDefault(i =>
            i.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>");
        return enumerable?.TypeArguments.FirstOrDefault()?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static ITypeSymbol? GetUnderlyingTypeSymbol(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.IsGenericType &&
            named.ConstructedFrom.ToDisplayString() == "System.Nullable<T>")
        {
            return named.TypeArguments[0];
        }
        return null;
    }

    private void Execute(SourceProductionContext context, (Compilation compilation, ImmutableArray<EndpointInfo?> endpoints) tuple)
    {
        var (_, endpoints) = tuple;
        var validEndpoints = endpoints.Where(e => e is not null).Select(e => e!).ToList();
        if (validEndpoints.Count == 0) return;

        var namespaces = new HashSet<string>(StringComparer.Ordinal);
        var registrations = new List<string>();

        foreach (var endpoint in validEndpoints)
        {
            // Generate property accessor
            var accessorSource = GeneratePropertyAccessor(endpoint);
            context.AddSource($"{endpoint.TypeName}PropertyAccessor.g.cs", SourceText.From(accessorSource, Encoding.UTF8));

            // Generate filter builder
            if (endpoint.EnableFiltering)
            {
                var filterSource = GenerateFilterBuilder(endpoint);
                context.AddSource($"{endpoint.TypeName}FilterBuilder.g.cs", SourceText.From(filterSource, Encoding.UTF8));
            }

            // Generate order builder
            if (endpoint.EnableOrdering)
            {
                var orderSource = GenerateOrderBuilder(endpoint);
                context.AddSource($"{endpoint.TypeName}OrderBuilder.g.cs", SourceText.From(orderSource, Encoding.UTF8));
            }

            namespaces.Add(endpoint.Namespace);
            registrations.Add($"            services.AddSingleton<IKyrolusPropertyAccessor<{endpoint.FullTypeName}>, {endpoint.TypeName}PropertyAccessor>();");
            if (endpoint.EnableFiltering)
            {
                registrations.Add($"            services.AddSingleton<IKyrolusStaticFilterBuilder<{endpoint.FullTypeName}>, {endpoint.TypeName}FilterBuilder>();");
            }
            if (endpoint.EnableOrdering)
            {
                registrations.Add($"            services.AddSingleton<IKyrolusStaticOrderBuilder<{endpoint.FullTypeName}>, {endpoint.TypeName}OrderBuilder>();");
            }
        }

        // Generate DI extensions
        EmitDiExtensions(context, namespaces, registrations);

        // Generate endpoint handler registration helper
        EmitEndpointHandlerRegistry(context, validEndpoints);
    }

    private string GeneratePropertyAccessor(EndpointInfo endpoint)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using KyrolusSous.EndpointKit.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {endpoint.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>AOT-safe property accessor for <see cref=\"{endpoint.TypeName}\"/>.</summary>");
        sb.AppendLine($"    public sealed class {endpoint.TypeName}PropertyAccessor : IKyrolusPropertyAccessor<{endpoint.FullTypeName}>");
        sb.AppendLine("    {");

        // Static property info cache
        sb.AppendLine("        private static readonly Dictionary<string, KyrolusPropertyInfo> _propertyMap = new(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("        {");
        foreach (var prop in endpoint.Properties)
        {
            sb.AppendLine($"            {{ \"{prop.Name}\", new KyrolusPropertyInfo(\"{prop.Name}\", typeof({prop.FullTypeName}), {prop.IsNullable.ToString().ToLower()}, {prop.HasSetter.ToString().ToLower()}) }},");
        }
        sb.AppendLine("        };");
        sb.AppendLine();

        // GetPropertyInfo
        sb.AppendLine("        public KyrolusPropertyInfo? GetPropertyInfo(string propertyName)");
        sb.AppendLine("            => _propertyMap.TryGetValue(propertyName, out var info) ? info : null;");
        sb.AppendLine();

        // GetPropertyNames
        sb.AppendLine("        public IReadOnlyList<string> GetPropertyNames()");
        sb.AppendLine("            => _propertyMap.Keys.ToList();");
        sb.AppendLine();

        // TryGetValue - static switch for AOT
        sb.AppendLine($"        public bool TryGetValue({endpoint.FullTypeName} instance, string propertyName, out object? value)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (propertyName.ToLowerInvariant())");
        sb.AppendLine("            {");
        foreach (var prop in endpoint.Properties)
        {
            sb.AppendLine($"                case \"{prop.Name.ToLowerInvariant()}\":");
            sb.AppendLine($"                    value = instance.{prop.Name};");
            sb.AppendLine("                    return true;");
        }
        sb.AppendLine("                default:");
        sb.AppendLine("                    value = null;");
        sb.AppendLine("                    return false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // TrySetValue - static switch for AOT
        sb.AppendLine($"        public bool TrySetValue({endpoint.FullTypeName} instance, string propertyName, object? value)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (propertyName.ToLowerInvariant())");
        sb.AppendLine("            {");
        foreach (var prop in endpoint.Properties.Where(p => p.HasSetter))
        {
            sb.AppendLine($"                case \"{prop.Name.ToLowerInvariant()}\":");
            sb.AppendLine($"                    instance.{prop.Name} = ({prop.FullTypeName})value!;");
            sb.AppendLine("                    return true;");
        }
        sb.AppendLine("                default:");
        sb.AppendLine("                    return false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // GetMemberAccessExpression - generates expression for each property
        sb.AppendLine($"        public Expression<Func<{endpoint.FullTypeName}, object?>>? GetMemberAccessExpression(string propertyName)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (propertyName.ToLowerInvariant())");
        sb.AppendLine("            {");
        foreach (var prop in endpoint.Properties)
        {
            sb.AppendLine($"                case \"{prop.Name.ToLowerInvariant()}\":");
            sb.AppendLine($"                    return x => (object?)x.{prop.Name};");
        }
        sb.AppendLine("                default:");
        sb.AppendLine("                    return null;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private string GenerateFilterBuilder(EndpointInfo endpoint)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using KyrolusSous.EndpointKit.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {endpoint.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>AOT-safe filter expression builder for <see cref=\"{endpoint.TypeName}\"/>.</summary>");
        sb.AppendLine($"    public sealed class {endpoint.TypeName}FilterBuilder : IKyrolusStaticFilterBuilder<{endpoint.FullTypeName}>");
        sb.AppendLine("    {");

        // Allowed properties set
        if (!endpoint.AllowedFilterProperties.IsDefaultOrEmpty)
        {
            sb.AppendLine("        private static readonly HashSet<string> _allowedProperties = new(StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine("        {");
            foreach (var prop in endpoint.AllowedFilterProperties)
            {
                sb.AppendLine($"            \"{prop}\",");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        // BuildFilterExpression
        sb.AppendLine($"        public bool TryBuildFilterExpression(");
        sb.AppendLine("            string propertyName,");
        sb.AppendLine("            string operatorName,");
        sb.AppendLine("            string? value,");
        sb.AppendLine($"            out Expression<Func<{endpoint.FullTypeName}, bool>>? expression,");
        sb.AppendLine("            out string? error)");
        sb.AppendLine("        {");
        sb.AppendLine("            expression = null;");
        sb.AppendLine("            error = null;");

        if (!endpoint.AllowedFilterProperties.IsDefaultOrEmpty)
        {
            sb.AppendLine("            if (!_allowedProperties.Contains(propertyName))");
            sb.AppendLine("            {");
            sb.AppendLine("                error = $\"Filtering by '{propertyName}' is not allowed.\";");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("            var normalizedOp = NormalizeOperator(operatorName);");
        sb.AppendLine("            switch (propertyName.ToLowerInvariant())");
        sb.AppendLine("            {");

        foreach (var prop in endpoint.Properties)
        {
            sb.AppendLine($"                case \"{prop.Name.ToLowerInvariant()}\":");
            sb.AppendLine($"                    return TryBuild{prop.Name}Filter(normalizedOp, value, out expression, out error);");
        }

        sb.AppendLine("                default:");
        sb.AppendLine($"                    error = $\"Property '{{propertyName}}' not found on {endpoint.TypeName}.\";");
        sb.AppendLine("                    return false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generate individual property filter methods
        foreach (var prop in endpoint.Properties)
        {
            GeneratePropertyFilterMethod(sb, endpoint, prop);
        }

        // Helper methods
        GenerateFilterHelperMethods(sb);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GeneratePropertyFilterMethod(StringBuilder sb, EndpointInfo endpoint, PropertyInfo prop)
    {
        sb.AppendLine($"        private static bool TryBuild{prop.Name}Filter(");
        sb.AppendLine("            string op,");
        sb.AppendLine("            string? value,");
        sb.AppendLine($"            out Expression<Func<{endpoint.FullTypeName}, bool>>? expression,");
        sb.AppendLine("            out string? error)");
        sb.AppendLine("        {");
        sb.AppendLine("            expression = null;");
        sb.AppendLine("            error = null;");
        sb.AppendLine();

        // Handle null checks first
        sb.AppendLine("            if (op == \"isnull\")");
        sb.AppendLine("            {");
        if (prop.IsNullable || prop.IsString)
        {
            sb.AppendLine($"                expression = x => x.{prop.Name} == null;");
        }
        else
        {
            sb.AppendLine($"                expression = x => false; // {prop.Name} is non-nullable");
        }
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine();

        sb.AppendLine("            if (op == \"notnull\")");
        sb.AppendLine("            {");
        if (prop.IsNullable || prop.IsString)
        {
            sb.AppendLine($"                expression = x => x.{prop.Name} != null;");
        }
        else
        {
            sb.AppendLine($"                expression = x => true; // {prop.Name} is non-nullable");
        }
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine();

        // Type-specific operations
        if (prop.IsString)
        {
            GenerateStringFilterOperations(sb, prop);
        }
        else if (prop.IsNumeric)
        {
            GenerateNumericFilterOperations(sb, prop);
        }
        else if (prop.IsBoolean)
        {
            GenerateBooleanFilterOperations(sb, prop);
        }
        else if (prop.IsDateTime)
        {
            GenerateDateTimeFilterOperations(sb, prop);
        }
        else if (prop.IsGuid)
        {
            GenerateGuidFilterOperations(sb, prop);
        }
        else if (prop.IsEnum)
        {
            GenerateEnumFilterOperations(sb, prop);
        }
        else
        {
            // Default: only eq supported
            sb.AppendLine("            if (op == \"eq\")");
            sb.AppendLine("            {");
            sb.AppendLine($"                error = \"Only 'eq' operator is supported for {prop.Name}.\";");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine($"            error = $\"Operator '{{op}}' is not supported for property '{prop.Name}'.\";");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void GenerateStringFilterOperations(StringBuilder sb, PropertyInfo prop)
    {
        sb.AppendLine("            if (string.IsNullOrEmpty(value))");
        sb.AppendLine("            {");
        sb.AppendLine("                error = \"Value is required for string comparison.\";");
        sb.AppendLine("                return false;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            switch (op)");
        sb.AppendLine("            {");
        sb.AppendLine("                case \"eq\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} == value;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"ne\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} != value;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"contains\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} != null && x.{prop.Name}.Contains(value);");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"startswith\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} != null && x.{prop.Name}.StartsWith(value);");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"endswith\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} != null && x.{prop.Name}.EndsWith(value);");
        sb.AppendLine("                    return true;");
        sb.AppendLine("            }");
    }

    private void GenerateNumericFilterOperations(StringBuilder sb, PropertyInfo prop)
    {
        var underlyingType = prop.UnderlyingType ?? prop.FullTypeName;
        sb.AppendLine($"            if (!TryParseNumeric(value, out {underlyingType} parsed))");
        sb.AppendLine("            {");
        sb.AppendLine($"                error = $\"Could not convert '{{value}}' to {prop.ShortTypeName}.\";");
        sb.AppendLine("                return false;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            switch (op)");
        sb.AppendLine("            {");
        sb.AppendLine("                case \"eq\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} == parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"ne\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} != parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"gt\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} > parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"gte\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} >= parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"lt\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} < parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"lte\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} <= parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("            }");
    }

    private void GenerateBooleanFilterOperations(StringBuilder sb, PropertyInfo prop)
    {
        sb.AppendLine("            if (!bool.TryParse(value, out var parsed))");
        sb.AppendLine("            {");
        sb.AppendLine($"                error = $\"Could not convert '{{value}}' to bool.\";");
        sb.AppendLine("                return false;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (op == \"eq\")");
        sb.AppendLine("            {");
        sb.AppendLine($"                expression = x => x.{prop.Name} == parsed;");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine("            if (op == \"ne\")");
        sb.AppendLine("            {");
        sb.AppendLine($"                expression = x => x.{prop.Name} != parsed;");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
    }

    private void GenerateDateTimeFilterOperations(StringBuilder sb, PropertyInfo prop)
    {
        var underlyingType = prop.UnderlyingType ?? prop.FullTypeName;
        sb.AppendLine($"            if (!TryParseDateTime(value, out {underlyingType} parsed))");
        sb.AppendLine("            {");
        sb.AppendLine($"                error = $\"Could not convert '{{value}}' to {prop.ShortTypeName}.\";");
        sb.AppendLine("                return false;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            switch (op)");
        sb.AppendLine("            {");
        sb.AppendLine("                case \"eq\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} == parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"ne\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} != parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"gt\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} > parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"gte\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} >= parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"lt\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} < parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                case \"lte\":");
        sb.AppendLine($"                    expression = x => x.{prop.Name} <= parsed;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("            }");
    }

    private void GenerateGuidFilterOperations(StringBuilder sb, PropertyInfo prop)
    {
        sb.AppendLine("            if (!Guid.TryParse(value, out var parsed))");
        sb.AppendLine("            {");
        sb.AppendLine($"                error = $\"Could not convert '{{value}}' to Guid.\";");
        sb.AppendLine("                return false;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (op == \"eq\")");
        sb.AppendLine("            {");
        sb.AppendLine($"                expression = x => x.{prop.Name} == parsed;");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine("            if (op == \"ne\")");
        sb.AppendLine("            {");
        sb.AppendLine($"                expression = x => x.{prop.Name} != parsed;");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
    }

    private void GenerateEnumFilterOperations(StringBuilder sb, PropertyInfo prop)
    {
        var underlyingType = prop.UnderlyingType ?? prop.FullTypeName;
        sb.AppendLine($"            if (!Enum.TryParse<{underlyingType}>(value, true, out var parsed))");
        sb.AppendLine("            {");
        sb.AppendLine($"                error = $\"Could not convert '{{value}}' to {prop.ShortTypeName}.\";");
        sb.AppendLine("                return false;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (op == \"eq\")");
        sb.AppendLine("            {");
        sb.AppendLine($"                expression = x => x.{prop.Name} == parsed;");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine("            if (op == \"ne\")");
        sb.AppendLine("            {");
        sb.AppendLine($"                expression = x => x.{prop.Name} != parsed;");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
    }

    private void GenerateFilterHelperMethods(StringBuilder sb)
    {
        sb.AppendLine(@"        private static string NormalizeOperator(string op)
        {
            var lower = op.Trim().ToLowerInvariant();
            return lower switch
            {
                ""="" or ""eq"" or ""equals"" => ""eq"",
                ""!="" or ""ne"" or ""notequals"" => ""ne"",
                "">"" or ""gt"" => ""gt"",
                "">="" or ""gte"" => ""gte"",
                ""<"" or ""lt"" => ""lt"",
                ""<="" or ""lte"" => ""lte"",
                _ => lower
            };
        }

        private static bool TryParseNumeric<T>(string? value, out T result) where T : struct
        {
            result = default;
            if (string.IsNullOrWhiteSpace(value)) return false;
            try
            {
                result = (T)Convert.ChangeType(value, typeof(T), CultureInfo.InvariantCulture);
                return true;
            }
            catch
            {
                return false;
            }
        }

        private static bool TryParseDateTime(string? value, out DateTime result)
        {
            result = default;
            if (string.IsNullOrWhiteSpace(value)) return false;
            return DateTime.TryParse(value, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out result);
        }

        private static bool TryParseDateTime(string? value, out DateTimeOffset result)
        {
            result = default;
            if (string.IsNullOrWhiteSpace(value)) return false;
            return DateTimeOffset.TryParse(value, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out result);
        }");
    }

    private string GenerateOrderBuilder(EndpointInfo endpoint)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using KyrolusSous.EndpointKit.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {endpoint.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>AOT-safe order expression builder for <see cref=\"{endpoint.TypeName}\"/>.</summary>");
        sb.AppendLine($"    public sealed class {endpoint.TypeName}OrderBuilder : IKyrolusStaticOrderBuilder<{endpoint.FullTypeName}>");
        sb.AppendLine("    {");

        // Allowed properties set
        if (!endpoint.AllowedOrderProperties.IsDefaultOrEmpty)
        {
            sb.AppendLine("        private static readonly HashSet<string> _allowedProperties = new(StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine("        {");
            foreach (var prop in endpoint.AllowedOrderProperties)
            {
                sb.AppendLine($"            \"{prop}\",");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        // TryBuildOrderExpression
        sb.AppendLine($"        public bool TryBuildOrderExpression(");
        sb.AppendLine("            string propertyName,");
        sb.AppendLine("            bool descending,");
        sb.AppendLine("            bool isFirst,");
        sb.AppendLine($"            IQueryable<{endpoint.FullTypeName}> query,");
        sb.AppendLine($"            out IOrderedQueryable<{endpoint.FullTypeName}>? result,");
        sb.AppendLine("            out string? error)");
        sb.AppendLine("        {");
        sb.AppendLine("            result = null;");
        sb.AppendLine("            error = null;");

        if (!endpoint.AllowedOrderProperties.IsDefaultOrEmpty)
        {
            sb.AppendLine("            if (!_allowedProperties.Contains(propertyName))");
            sb.AppendLine("            {");
            sb.AppendLine("                error = $\"Ordering by '{propertyName}' is not allowed.\";");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("            switch (propertyName.ToLowerInvariant())");
        sb.AppendLine("            {");

        foreach (var prop in endpoint.Properties)
        {
            sb.AppendLine($"                case \"{prop.Name.ToLowerInvariant()}\":");
            sb.AppendLine("                    result = ApplyOrder(query, isFirst, descending,");
            sb.AppendLine($"                        x => x.{prop.Name});");
            sb.AppendLine("                    return true;");
        }

        sb.AppendLine("                default:");
        sb.AppendLine($"                    error = $\"Property '{{propertyName}}' not found on {endpoint.TypeName}.\";");
        sb.AppendLine("                    return false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // GetSupportedProperties
        sb.AppendLine("        public IReadOnlyList<string> GetSupportedProperties()");
        sb.AppendLine("            => new[]");
        sb.AppendLine("            {");
        foreach (var prop in endpoint.Properties)
        {
            sb.AppendLine($"                \"{prop.Name}\",");
        }
        sb.AppendLine("            };");
        sb.AppendLine();

        // Helper method
        sb.AppendLine($@"        private static IOrderedQueryable<{endpoint.FullTypeName}> ApplyOrder<TKey>(
            IQueryable<{endpoint.FullTypeName}> query,
            bool isFirst,
            bool descending,
            Expression<Func<{endpoint.FullTypeName}, TKey>> selector)
        {{
            if (isFirst)
            {{
                return descending
                    ? query.OrderByDescending(selector)
                    : query.OrderBy(selector);
            }}
            return descending
                ? ((IOrderedQueryable<{endpoint.FullTypeName}>)query).ThenByDescending(selector)
                : ((IOrderedQueryable<{endpoint.FullTypeName}>)query).ThenBy(selector);
        }}");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitDiExtensions(SourceProductionContext context, HashSet<string> namespaces, List<string> registrations)
    {
        if (registrations.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using KyrolusSous.EndpointKit.Core;");
        foreach (var ns in namespaces.OrderBy(n => n))
        {
            sb.AppendLine($"using {ns};");
        }
        sb.AppendLine();
        sb.AppendLine("namespace KyrolusSous.EndpointKit.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Generated extension methods for registering AOT endpoint services.</summary>");
        sb.AppendLine("    public static class KyrolusEndpointGeneratedServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Registers all generated property accessors, filter builders, and order builders.</summary>");
        sb.AppendLine("        public static IServiceCollection AddKyrolusGeneratedEndpoints(this IServiceCollection services)");
        sb.AppendLine("        {");
        foreach (var reg in registrations)
        {
            sb.AppendLine(reg);
        }
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("KyrolusEndpointGeneratedServiceCollectionExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitEndpointHandlerRegistry(SourceProductionContext context, List<EndpointInfo> endpoints)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using KyrolusSous.EndpointKit.Core;");
        sb.AppendLine();
        sb.AppendLine("namespace KyrolusSous.EndpointKit.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Registry of all generated endpoint types.</summary>");
        sb.AppendLine("    public static class KyrolusEndpointRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Gets all entity types that have generated endpoint support.</summary>");
        sb.AppendLine("        public static IReadOnlyList<KyrolusEndpointMetadata> GetRegisteredEndpoints()");
        sb.AppendLine("            => new KyrolusEndpointMetadata[]");
        sb.AppendLine("            {");

        foreach (var ep in endpoints)
        {
            sb.AppendLine($"                new(\"{ep.TypeName}\", typeof({ep.FullTypeName}), \"{ep.KeyProperty}\", typeof({ep.KeyType}), {(ep.SoftDeleteProperty is not null ? $"\"{ep.SoftDeleteProperty}\"" : "null")}, {(ep.TenantIdProperty is not null ? $"\"{ep.TenantIdProperty}\"" : "null")}, {ep.EnableFiltering.ToString().ToLower()}, {ep.EnableOrdering.ToString().ToLower()}),");
        }

        sb.AppendLine("            };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("KyrolusEndpointRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    #region Source Templates

    private const string AttributeSource = @"// <auto-generated />
#nullable enable

namespace KyrolusSous.EndpointKit.Core
{
    /// <summary>
    /// Marks an entity type for AOT-compatible endpoint generation.
    /// The source generator will create property accessors, filter builders,
    /// and order builders that work without runtime reflection.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    public sealed class KyrolusAotEndpointAttribute : System.Attribute
    {
        /// <summary>Creates a new instance with default settings.</summary>
        public KyrolusAotEndpointAttribute() { }

        /// <summary>Creates a new instance with the specified key property.</summary>
        /// <param name=""keyProperty"">The name of the key property (default: ""Id"").</param>
        public KyrolusAotEndpointAttribute(string keyProperty)
        {
            KeyProperty = keyProperty;
        }

        /// <summary>The name of the key property (default: ""Id"").</summary>
        public string KeyProperty { get; set; } = ""Id"";

        /// <summary>The type of the key property. If not specified, it will be inferred from the KeyProperty.</summary>
        public System.Type? KeyType { get; set; }

        /// <summary>The name of the soft delete property (e.g., ""IsDeleted""). If set, soft delete support is enabled.</summary>
        public string? SoftDeleteProperty { get; set; }

        /// <summary>The name of the row version property for optimistic concurrency.</summary>
        public string? RowVersionProperty { get; set; }

        /// <summary>The name of the tenant ID property for multi-tenancy support.</summary>
        public string? TenantIdProperty { get; set; }

        /// <summary>Enable filter expression generation (default: true).</summary>
        public bool EnableFiltering { get; set; } = true;

        /// <summary>Enable order expression generation (default: true).</summary>
        public bool EnableOrdering { get; set; } = true;

        /// <summary>List of property names allowed for filtering. If empty, all properties are allowed.</summary>
        public string[]? AllowedFilterProperties { get; set; }

        /// <summary>List of property names allowed for ordering. If empty, all properties are allowed.</summary>
        public string[]? AllowedOrderProperties { get; set; }
    }
}
";

    private const string PropertyAccessorBaseSource = @"// <auto-generated />
#nullable enable

namespace KyrolusSous.EndpointKit.Core
{
    /// <summary>Provides AOT-safe property access for an entity type.</summary>
    public interface IKyrolusPropertyAccessor<T> where T : class
    {
        /// <summary>Gets property information by name.</summary>
        KyrolusPropertyInfo? GetPropertyInfo(string propertyName);

        /// <summary>Gets all property names.</summary>
        System.Collections.Generic.IReadOnlyList<string> GetPropertyNames();

        /// <summary>Gets a property value without reflection.</summary>
        bool TryGetValue(T instance, string propertyName, out object? value);

        /// <summary>Sets a property value without reflection.</summary>
        bool TrySetValue(T instance, string propertyName, object? value);

        /// <summary>Gets a member access expression for the property.</summary>
        System.Linq.Expressions.Expression<System.Func<T, object?>>? GetMemberAccessExpression(string propertyName);
    }

    /// <summary>Metadata about a property.</summary>
    public sealed class KyrolusPropertyInfo
    {
        public KyrolusPropertyInfo(string name, System.Type type, bool isNullable, bool hasSetter)
        {
            Name = name;
            Type = type;
            IsNullable = isNullable;
            HasSetter = hasSetter;
        }

        public string Name { get; }
        public System.Type Type { get; }
        public bool IsNullable { get; }
        public bool HasSetter { get; }
    }

    /// <summary>Metadata about an endpoint.</summary>
    public sealed class KyrolusEndpointMetadata
    {
        public KyrolusEndpointMetadata(
            string typeName,
            System.Type entityType,
            string keyProperty,
            System.Type keyType,
            string? softDeleteProperty,
            string? tenantIdProperty,
            bool enableFiltering,
            bool enableOrdering)
        {
            TypeName = typeName;
            EntityType = entityType;
            KeyProperty = keyProperty;
            KeyType = keyType;
            SoftDeleteProperty = softDeleteProperty;
            TenantIdProperty = tenantIdProperty;
            EnableFiltering = enableFiltering;
            EnableOrdering = enableOrdering;
        }

        public string TypeName { get; }
        public System.Type EntityType { get; }
        public string KeyProperty { get; }
        public System.Type KeyType { get; }
        public string? SoftDeleteProperty { get; }
        public string? TenantIdProperty { get; }
        public bool EnableFiltering { get; }
        public bool EnableOrdering { get; }
    }
}
";

    private const string StaticFilterBuilderBaseSource = @"// <auto-generated />
#nullable enable

namespace KyrolusSous.EndpointKit.Core
{
    /// <summary>Provides AOT-safe filter expression building for an entity type.</summary>
    public interface IKyrolusStaticFilterBuilder<T> where T : class
    {
        /// <summary>
        /// Tries to build a filter expression for the specified property and operator.
        /// </summary>
        /// <param name=""propertyName"">The property name to filter on.</param>
        /// <param name=""operatorName"">The filter operator (eq, ne, gt, gte, lt, lte, contains, startswith, endswith, isnull, notnull).</param>
        /// <param name=""value"">The value to compare against.</param>
        /// <param name=""expression"">The resulting filter expression if successful.</param>
        /// <param name=""error"">Error message if the operation failed.</param>
        /// <returns>True if the expression was built successfully.</returns>
        bool TryBuildFilterExpression(
            string propertyName,
            string operatorName,
            string? value,
            out System.Linq.Expressions.Expression<System.Func<T, bool>>? expression,
            out string? error);
    }
}
";

    private const string StaticOrderBuilderBaseSource = @"// <auto-generated />
#nullable enable

namespace KyrolusSous.EndpointKit.Core
{
    /// <summary>Provides AOT-safe order expression building for an entity type.</summary>
    public interface IKyrolusStaticOrderBuilder<T> where T : class
    {
        /// <summary>
        /// Tries to build an order expression for the specified property.
        /// </summary>
        /// <param name=""propertyName"">The property name to order by.</param>
        /// <param name=""descending"">True for descending order.</param>
        /// <param name=""isFirst"">True if this is the first order clause (uses OrderBy vs ThenBy).</param>
        /// <param name=""query"">The query to apply ordering to.</param>
        /// <param name=""result"">The ordered queryable if successful.</param>
        /// <param name=""error"">Error message if the operation failed.</param>
        /// <returns>True if ordering was applied successfully.</returns>
        bool TryBuildOrderExpression(
            string propertyName,
            bool descending,
            bool isFirst,
            System.Linq.IQueryable<T> query,
            out System.Linq.IOrderedQueryable<T>? result,
            out string? error);

        /// <summary>Gets the list of properties that support ordering.</summary>
        System.Collections.Generic.IReadOnlyList<string> GetSupportedProperties();
    }
}
";

    #endregion

    #region Types

    private sealed class EndpointInfo
    {
        public EndpointInfo(
            string typeName,
            string ns,
            string fullTypeName,
            string keyProperty,
            string keyType,
            string? softDeleteProperty,
            string? rowVersionProperty,
            string? tenantIdProperty,
            bool enableFiltering,
            bool enableOrdering,
            ImmutableArray<string> allowedFilterProperties,
            ImmutableArray<string> allowedOrderProperties,
            ImmutableArray<PropertyInfo> properties)
        {
            TypeName = typeName;
            Namespace = ns;
            FullTypeName = fullTypeName;
            KeyProperty = keyProperty;
            KeyType = keyType;
            SoftDeleteProperty = softDeleteProperty;
            RowVersionProperty = rowVersionProperty;
            TenantIdProperty = tenantIdProperty;
            EnableFiltering = enableFiltering;
            EnableOrdering = enableOrdering;
            AllowedFilterProperties = allowedFilterProperties;
            AllowedOrderProperties = allowedOrderProperties;
            Properties = properties;
        }

        public string TypeName { get; }
        public string Namespace { get; }
        public string FullTypeName { get; }
        public string KeyProperty { get; }
        public string KeyType { get; }
        public string? SoftDeleteProperty { get; }
        public string? RowVersionProperty { get; }
        public string? TenantIdProperty { get; }
        public bool EnableFiltering { get; }
        public bool EnableOrdering { get; }
        public ImmutableArray<string> AllowedFilterProperties { get; }
        public ImmutableArray<string> AllowedOrderProperties { get; }
        public ImmutableArray<PropertyInfo> Properties { get; }
    }

    private sealed class PropertyInfo
    {
        public PropertyInfo(
            string name,
            string fullTypeName,
            string shortTypeName,
            bool hasSetter,
            bool isNullable,
            string? underlyingType,
            bool isNumeric,
            bool isString,
            bool isBoolean,
            bool isDateTime,
            bool isGuid,
            bool isEnum,
            bool isCollection,
            string? collectionElementType)
        {
            Name = name;
            FullTypeName = fullTypeName;
            ShortTypeName = shortTypeName;
            HasSetter = hasSetter;
            IsNullable = isNullable;
            UnderlyingType = underlyingType;
            IsNumeric = isNumeric;
            IsString = isString;
            IsBoolean = isBoolean;
            IsDateTime = isDateTime;
            IsGuid = isGuid;
            IsEnum = isEnum;
            IsCollection = isCollection;
            CollectionElementType = collectionElementType;
        }

        public string Name { get; }
        public string FullTypeName { get; }
        public string ShortTypeName { get; }
        public bool HasSetter { get; }
        public bool IsNullable { get; }
        public string? UnderlyingType { get; }
        public bool IsNumeric { get; }
        public bool IsString { get; }
        public bool IsBoolean { get; }
        public bool IsDateTime { get; }
        public bool IsGuid { get; }
        public bool IsEnum { get; }
        public bool IsCollection { get; }
        public string? CollectionElementType { get; }
    }

    #endregion
}
