<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13.0</LangVersion>
    <RootNamespace>KyrolusSous.Audit.Core</RootNamespace>
    <Description>Enterprise entity change tracking, EF Core audit interceptors, and audit storage services for KyrolusSous toolkit.</Description>
    <PackageTags>audit;auditing;compliance;entityframework;history;tracking</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KyrolusSous.Audit.Abstractions\KyrolusSous.Audit.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
  </ItemGroup>

</Project>
