// <auto-generated />
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using KyrolusSous.Repositories.Marten.Abstractions.Interfaces;

namespace KyrolusSous.Repositories.Marten.Abstractions.Query
{
    public interface IQueryHelper<TEntity>
    {
        QueryParts<TEntity> Build(QueryRequest? request);
        Expression<Func<TEntity, bool>>? BuildFilter(QueryRequest? request);
        Func<IQueryable<TEntity>, IOrderedQueryable<TEntity>>? BuildOrderBy(QueryRequest? request);
        Expression<Func<TEntity, object?>>[] BuildIncludes(QueryRequest? request);
    }

    public sealed record OrderClause(string Property, bool Desc = false);
    public sealed record FilterClause(string Property, string Operator, string? Value);
    public sealed partial record QueryRequest(
        string[]? Includes = null,
        string[]? Fields = null,
        OrderClause[]? OrderBy = null,
        FilterClause[]? Filters = null,
        bool? AsNoTracking = null,
        bool? UseSplitQuery = null,
        bool? IncludeDeleted = null,
        object? IncludeGraph = null);

    public sealed partial record QueryRequest : IParsable<QueryRequest>
    {
        public static QueryRequest Parse(string s, IFormatProvider? provider)
            => TryParse(s, provider, out var result) ? result : throw new FormatException("Invalid QueryRequest format.");

        public static bool TryParse(string? s, IFormatProvider? provider, out QueryRequest result)
        {
            if (string.IsNullOrWhiteSpace(s))
            {
                result = new QueryRequest();
                return true;
            }

            try
            {
                var decoded = WebUtility.UrlDecode(s);
                result = System.Text.Json.JsonSerializer.Deserialize<QueryRequest>(decoded, new System.Text.Json.JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                }) ?? new QueryRequest();
                return true;
            }
            catch
            {
                result = new QueryRequest();
                return false;
            }
        }
    }

    public sealed record QueryParts<TEntity>(
        Expression<Func<TEntity, bool>>? Filter,
        Func<IQueryable<TEntity>, IOrderedQueryable<TEntity>>? OrderBy,
        Expression<Func<TEntity, object?>>[] Includes,
        bool? AsNoTracking = null,
        bool? UseSplitQuery = null,
        bool? IncludeDeleted = null,
        IncludeGraph<TEntity>? IncludeGraph = null);
}
