namespace KyrolusSous.Caching.Redis;

/// <summary>
/// Comprehensive configuration options for the Kyrolus Redis Caching provider.
/// Supports compression, encryption, distributed locking, pattern invalidation, circuit breakers, 
/// telemetry, and multi-tenant namespaces.
/// </summary>
public sealed class KyrolusRedisCacheOptions
{
    /// <summary>
    /// Gets or sets the Redis connection string (e.g. <c>"localhost:6379,abortConnect=false,ssl=true"</c>).
    /// </summary>
    public string? ConnectionString { get; set; }

    /// <summary>
    /// Gets or sets a global key prefix prepended to all Redis keys generated by this application.
    /// </summary>
    /// <remarks>
    /// <b>Real-World Use Case (Shared Redis Instance):</b>
    /// When three separate applications (e.g. "Storefront", "AdminPanel", "Warehouse") share a single Redis instance, 
    /// setting <c>KeyPrefix = "storefront"</c> isolates their keys and prevents accidental overwrites or collisions.
    /// </remarks>
    public string? KeyPrefix { get; set; }

    /// <summary>
    /// Gets or sets the Redis Set key name used to track active cache keys when <see cref="PatternRemovalStrategy"/> is set to <see cref="KyrolusRedisPatternRemovalStrategy.KeyIndex"/>.
    /// Defaults to <c>"kyrolus:cache:index"</c>.
    /// </summary>
    public string KeyIndexKey { get; set; } = "kyrolus:cache:index";

    /// <summary>
    /// Gets or sets the maximum chunk size when executing batch operations (e.g. <c>GetManyAsync</c>, <c>SetManyAsync</c>, <c>RemoveManyAsync</c>). 
    /// Defaults to 256.
    /// </summary>
    /// <remarks>
    /// <b>Real-World Use Case:</b>
    /// If an operation deletes 10,000 keys at once, chunking them into batches of 256 prevents blocking the Redis single-threaded event loop.
    /// </remarks>
    public int BatchSize { get; set; } = 256;

    /// <summary>
    /// Gets or sets the default absolute Time-To-Live duration. Defaults to 30 minutes.
    /// </summary>
    public TimeSpan? DefaultTtl { get; set; } = KyrolusCacheDefaults.DefaultTtl;

    /// <summary>
    /// Gets or sets the default sliding expiration duration. Defaults to 5 minutes.
    /// </summary>
    public TimeSpan? DefaultSlidingTtl { get; set; } = KyrolusCacheDefaults.DefaultSlidingTtl;

    /// <summary>
    /// Gets or sets the default expiration TTL for negative/null results to defend against Cache Penetration attacks.
    /// </summary>
    public TimeSpan? DefaultNegativeTtl { get; set; }

    /// <summary>
    /// Gets or sets the auto-expiration lease duration (TTL) for acquired distributed locks. Defaults to 10 seconds.
    /// </summary>
    /// <remarks>
    /// <b>Real-World Use Case:</b>
    /// Automatically unlocks contested resources if the server holding the lock crashes or is terminated.
    /// </remarks>
    public TimeSpan? LockTtl { get; set; } = KyrolusCacheDefaults.DefaultLockTtl;

    /// <summary>
    /// Gets or sets the maximum duration to wait while polling to acquire a distributed lock before timing out. Defaults to 2 seconds.
    /// </summary>
    public TimeSpan? LockWait { get; set; } = KyrolusCacheDefaults.DefaultLockWait;

    /// <summary>
    /// Gets or sets the initial delay between polling attempts when trying to acquire a busy lock. Defaults to 50 milliseconds.
    /// </summary>
    public TimeSpan? LockRetryDelay { get; set; } = KyrolusCacheDefaults.DefaultLockRetryDelay;

    /// <summary>
    /// Gets or sets the backoff strategy (<see cref="KyrolusRedisLockBackoffMode.Fixed"/> or <see cref="KyrolusRedisLockBackoffMode.Exponential"/>) used when polling for locks.
    /// </summary>
    public KyrolusRedisLockBackoffMode LockBackoffMode { get; set; } = KyrolusRedisLockBackoffMode.Fixed;

    /// <summary>
    /// Gets or sets the exponential backoff multiplier applied when <see cref="LockBackoffMode"/> is set to Exponential. Defaults to 2.0.
    /// </summary>
    public double LockBackoffMultiplier { get; set; } = 2;

    /// <summary>
    /// Gets or sets the maximum upper bound delay between lock retry attempts.
    /// </summary>
    public TimeSpan? LockMaxRetryDelay { get; set; }

    /// <summary>
    /// Gets or sets the locking implementation strategy (<see cref="KyrolusRedisLockStrategy.Lua"/>, Simple, or Disabled). Defaults to Lua.
    /// </summary>
    public KyrolusRedisLockStrategy LockStrategy { get; set; } = KyrolusRedisLockStrategy.Lua;

    /// <summary>
    /// Gets or sets the strategy for executing wildcard pattern key removals. Defaults to <see cref="KyrolusRedisPatternRemovalStrategy.KeyIndex"/>.
    /// </summary>
    public KyrolusRedisPatternRemovalStrategy PatternRemovalStrategy { get; set; } = KyrolusRedisPatternRemovalStrategy.KeyIndex;

    /// <summary>
    /// Gets or sets the server role targeted for Redis SCAN operations (Primary, Replica, or Any). Defaults to Primary.
    /// </summary>
    public KyrolusRedisServerRole ScanServerRole { get; set; } = KyrolusRedisServerRole.Primary;

    /// <summary>
    /// Gets or sets StackExchange.Redis command flags applied to read operations (e.g. <see cref="CommandFlags.DemandReplica"/> to route reads to read-replicas).
    /// </summary>
    public CommandFlags ReadCommandFlags { get; set; } = CommandFlags.None;

    /// <summary>
    /// Gets or sets StackExchange.Redis command flags applied to write operations.
    /// </summary>
    public CommandFlags WriteCommandFlags { get; set; } = CommandFlags.None;

    /// <summary>
    /// Gets or sets whether automatic payload compression is enabled. Defaults to <c>false</c>.
    /// </summary>
    public bool EnableCompression { get; set; }

    /// <summary>
    /// Gets or sets the compression algorithm used when compression is enabled (Brotli, Zstd, LZ4, Snappy, Gzip, Deflate). Defaults to Brotli.
    /// </summary>
    public KyrolusCompressionAlgorithm KyrolusCompressionAlgorithm { get; set; } = KyrolusCompressionAlgorithm.Brotli;

    /// <summary>
    /// Gets or sets the minimum payload size in bytes before compression is applied. Defaults to 1024 bytes (1 KB).
    /// </summary>
    public int CompressionThresholdBytes { get; set; } = 1024;

    /// <summary>
    /// Gets or sets the compression quality/speed tradeoff level. Defaults to <see cref="CompressionLevel.Fastest"/>.
    /// </summary>
    public CompressionLevel CompressionLevel { get; set; } = KyrolusCacheDefaults.DefaultCompressionLevel;

    /// <summary>
    /// Gets or sets the execution priority order for compression in the pipeline. Defaults to 0 (runs before encryption).
    /// </summary>
    public int CompressionOrder { get; set; }

    /// <summary>
    /// Gets or sets whether payload encryption is enabled. Defaults to <c>false</c>.
    /// </summary>
    public bool EnableEncryption { get; set; }

    /// <summary>
    /// Gets or sets the AES symmetric key bytes (16, 24, or 32 bytes for AES-128/192/256).
    /// </summary>
    public byte[]? EncryptionKey { get; set; }

    /// <summary>
    /// Gets or sets the AES key encoded as a Base64 string.
    /// </summary>
    public string? EncryptionKeyBase64 { get; set; }

    /// <summary>
    /// Gets or sets an optional static 16-byte initialization vector. If null, a cryptographically random IV is generated per payload.
    /// </summary>
    public byte[]? EncryptionIv { get; set; }

    /// <summary>
    /// Gets or sets the static initialization vector encoded as a Base64 string.
    /// </summary>
    public string? EncryptionIvBase64 { get; set; }

    /// <summary>
    /// Gets or sets the execution priority order for encryption in the pipeline. Defaults to 100 (runs after compression).
    /// </summary>
    public int EncryptionOrder { get; set; } = 100;

    /// <summary>
    /// Gets or sets the Redis key used to store the hash signature of the current configuration (detects mismatched encryption/compression settings between releases).
    /// </summary>
    public string ConfigSignatureKey { get; set; } = "kyrolus:cache:config";

    /// <summary>
    /// Gets or sets a diagnostic delegate callback to receive internal non-fatal operational warnings.
    /// </summary>
    public Action<string>? WarningSink { get; set; }

    /// <summary>
    /// Gets or sets the default logical region name applied when operations do not supply an explicit region.
    /// </summary>
    public string? DefaultRegion { get; set; }

    /// <summary>
    /// Gets or sets the default tenant ID applied when operations do not supply an explicit tenant.
    /// </summary>
    public string? DefaultTenantId { get; set; }

    /// <summary>
    /// Gets or sets whether cache operations are strictly required to specify a region. Defaults to <c>false</c>.
    /// </summary>
    public bool RequireRegion { get; set; }

    /// <summary>
    /// Gets or sets whether cache operations are strictly required to specify a tenant ID. Defaults to <c>false</c>.
    /// </summary>
    public bool RequireTenantId { get; set; }

    /// <summary>
    /// Gets or sets whether cache operations should fail gracefully (return null / continue to DB) instead of throwing exceptions when Redis is down.
    /// </summary>
    public bool EnableGracefulFallback { get; set; }

    /// <summary>
    /// Gets or sets configuration settings for the Redis Circuit Breaker.
    /// </summary>
    public KyrolusRedisCircuitBreakerOptions CircuitBreaker { get; set; } = new();

    /// <summary>
    /// Sets the Redis connection string fluently.
    /// </summary>
    public KyrolusRedisCacheOptions UseConnectionString(string connectionString)
    {
        ConnectionString = connectionString;
        return this;
    }

    /// <summary>
    /// Sets the global key prefix fluently.
    /// </summary>
    public KyrolusRedisCacheOptions WithKeyPrefix(string prefix)
    {
        KeyPrefix = prefix;
        return this;
    }

    /// <summary>
    /// Sets the default absolute TTL fluently.
    /// </summary>
    public KyrolusRedisCacheOptions WithDefaultTtl(TimeSpan ttl)
    {
        DefaultTtl = ttl;
        return this;
    }

    /// <summary>
    /// Sets the default sliding TTL fluently.
    /// </summary>
    public KyrolusRedisCacheOptions WithSlidingTtl(TimeSpan slidingTtl)
    {
        DefaultSlidingTtl = slidingTtl;
        return this;
    }

    /// <summary>
    /// Sets the default negative caching TTL fluently.
    /// </summary>
    public KyrolusRedisCacheOptions WithNegativeTtl(TimeSpan negativeTtl)
    {
        DefaultNegativeTtl = negativeTtl;
        return this;
    }

    /// <summary>
    /// Configures payload compression with a specific algorithm, threshold, and compression level.
    /// </summary>
    public KyrolusRedisCacheOptions WithCompression(
        int thresholdBytes = 1024,
        CompressionLevel level = CompressionLevel.Fastest,
        KyrolusCompressionAlgorithm algorithm = KyrolusCompressionAlgorithm.Brotli)
    {
        EnableCompression = true;
        CompressionThresholdBytes = thresholdBytes;
        CompressionLevel = level;
        KyrolusCompressionAlgorithm = algorithm;
        return this;
    }

    /// <summary>
    /// Enables and configures Google Brotli payload compression.
    /// </summary>
    public KyrolusRedisCacheOptions WithBrotliCompression(
        int thresholdBytes = 1024,
        CompressionLevel level = CompressionLevel.Fastest) =>
        WithCompression(thresholdBytes, level, KyrolusCompressionAlgorithm.Brotli);

    /// <summary>
    /// Enables and configures Facebook Zstandard (Zstd) payload compression.
    /// </summary>
    public KyrolusRedisCacheOptions WithZstdCompression(
        int thresholdBytes = 1024,
        CompressionLevel level = CompressionLevel.Fastest) =>
        WithCompression(thresholdBytes, level, KyrolusCompressionAlgorithm.Zstd);

    /// <summary>
    /// Enables and configures ultra-fast LZ4 payload compression.
    /// </summary>
    public KyrolusRedisCacheOptions WithLz4Compression(
        int thresholdBytes = 1024,
        CompressionLevel level = CompressionLevel.Fastest) =>
        WithCompression(thresholdBytes, level, KyrolusCompressionAlgorithm.Lz4);

    /// <summary>
    /// Enables and configures Google Snappy payload compression.
    /// </summary>
    public KyrolusRedisCacheOptions WithSnappyCompression(
        int thresholdBytes = 1024,
        CompressionLevel level = CompressionLevel.Fastest) =>
        WithCompression(thresholdBytes, level, KyrolusCompressionAlgorithm.Snappy);

    /// <summary>
    /// Enables and configures standard Gzip payload compression.
    /// </summary>
    public KyrolusRedisCacheOptions WithGzipCompression(
        int thresholdBytes = 1024,
        CompressionLevel level = CompressionLevel.Fastest) =>
        WithCompression(thresholdBytes, level, KyrolusCompressionAlgorithm.Gzip);

    /// <summary>
    /// Enables and configures AES symmetric payload encryption with raw byte keys.
    /// </summary>
    public KyrolusRedisCacheOptions WithEncryption(byte[] key, byte[]? iv = null)
    {
        EnableEncryption = true;
        EncryptionKey = key;
        EncryptionIv = iv;
        return this;
    }

    /// <summary>
    /// Enables and configures AES symmetric payload encryption with Base64 encoded keys.
    /// </summary>
    public KyrolusRedisCacheOptions WithEncryptionBase64(string keyBase64, string? ivBase64 = null)
    {
        EnableEncryption = true;
        EncryptionKeyBase64 = keyBase64;
        EncryptionIvBase64 = ivBase64;
        return this;
    }

    /// <summary>
    /// Configures the Redis Circuit Breaker fluently.
    /// </summary>
    public KyrolusRedisCacheOptions WithCircuitBreaker(Action<KyrolusRedisCircuitBreakerOptions>? configure = null)
    {
        CircuitBreaker.Enabled = true;
        configure?.Invoke(CircuitBreaker);
        return this;
    }

    /// <summary>
    /// Configures the distributed lock strategy, default wait duration, and lease TTL.
    /// </summary>
    public KyrolusRedisCacheOptions WithLockStrategy(
        KyrolusRedisLockStrategy strategy,
        TimeSpan? defaultWait = null,
        TimeSpan? defaultTtl = null)
    {
        LockStrategy = strategy;
        if (defaultWait.HasValue) LockWait = defaultWait.Value;
        if (defaultTtl.HasValue) LockTtl = defaultTtl.Value;
        return this;
    }

    /// <summary>
    /// Configures graceful fallback to allow database reads without throwing exceptions when Redis is degraded.
    /// </summary>
    public KyrolusRedisCacheOptions WithGracefulFallback(bool enable = true)
    {
        EnableGracefulFallback = enable;
        return this;
    }

    /// <summary>
    /// Configures region and multi-tenant partitioning namespaces fluently.
    /// </summary>
    public KyrolusRedisCacheOptions WithNamespace(
        string? defaultRegion = null,
        string? defaultTenantId = null,
        bool requireRegion = false,
        bool requireTenantId = false)
    {
        DefaultRegion = defaultRegion;
        DefaultTenantId = defaultTenantId;
        RequireRegion = requireRegion;
        RequireTenantId = requireTenantId;
        return this;
    }
}
