<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>KyrolusSous.Compression</RootNamespace>
    <AssemblyName>KyrolusSous.Compression.Core</AssemblyName>
    <Description>Core HTTP response compression middleware, options, pipeline extensions, and compression provider registry.</Description>
    <Authors>Kyrolus Sous</Authors>
    <PackageTags>compression;aspnetcore;middleware;gzip;brotli;zstd;lz4;snappy</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KyrolusSous.Compression.Abstractions\KyrolusSous.Compression.Abstractions.csproj" />
  </ItemGroup>

</Project>
