using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KyrolusSous.SourceMediator.Interfaces
{

    /// <summary>
    /// Internal interface defining the contract for the generated dispatcher logic.
    /// This decouples the SourceSender runtime from the concrete generated class name.
    /// An implementation of this interface is expected to be generated by 
    /// SourceMediator.Generator and registered with the DI container.
    /// </summary>
    public interface IGeneratedDispatcher // Keep it internal to the SourceMediator library
    {
        /// <summary>
        /// Dispatches a request that expects a response (Queries or Commands returning TResponse).
        /// </summary>
        Task<TResponse> DispatchRequestAsync<TResponse>(object request, IServiceProvider sp, CancellationToken ct);

        /// <summary>
        /// Dispatches a command that does not return a value (handler returns Task).
        /// </summary>
        Task DispatchCommandAsync(object command, IServiceProvider sp, CancellationToken ct);
    }
}