// MediatorGenerator.cs
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

// Define the namespace for the generator project
namespace KyrolusSous.Mediator.Generator
{
    [Generator] // Mark this class as a Source Generator
    public class MediatorGenerator : IIncrementalGenerator
    {
        private const string AutoGeneratedHeader = "// <auto-generated/>";
        private const string NullableEnable = "#nullable enable";
        private const string CompilerGeneratedAttribute = "    [System.Runtime.CompilerServices.CompilerGenerated]";
        private const string OpenBrace = "{";
        private const string CloseBrace = "}";
        private const string Indent4OpenBrace = "    {";
        private const string Indent4CloseBrace = "    }";
        private const string Indent8OpenBrace = "        {";
        private const string Indent8CloseBrace = "        }";
        private const string Indent12OpenBrace = "            {";
        private const string Indent12CloseBrace = "            }";
        private const string Indent16OpenBrace = "                {";
        private const string Indent16CloseBrace = "                }";

        // --- Constants for necessary fully qualified type names ---
        // These names must exactly match the types defined in the KyrolusSous.Mediator.Abstractions library.
        private const string QueryHandlerInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusQueryHandler`2";
        private const string CommandHandlerInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusCommandHandler`1";
        private const string CommandHandlerWithResponseInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusCommandHandler`2";
        private const string RequestHandlerInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusRequestHandler`2";
        private const string RequestHandlerWithoutResponseInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusRequestHandler`1";
        private const string StreamRequestHandlerInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusStreamRequestHandler`2";
        private const string UnitTypeFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.Unit";
        // This interface is expected to be defined as 'internal' in the KyrolusSous.Mediator.Abstractions library
        private const string GeneratedDispatcherInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IGeneratedDispatcher";

        /// <summary>
        /// Called by the compiler to initialize the incremental generator pipeline.
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // STEP 1: Define the pipeline stage to find potential handler classes.
            // Filters syntax nodes for concrete (non-abstract, non-static) classes 
            // that have a base list (might implement interfaces or inherit).
            // Transforms the syntax node into its semantic symbol (INamedTypeSymbol).
            IncrementalValuesProvider<INamedTypeSymbol> handlerClassSymbols = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                    transform: static (ctx, ct) => GetSemanticTargetForGeneration(ctx, ct))
                .Where(static symbol => symbol is not null)!; // Ensure we only pass non-null symbols

            // STEP 2: Combine the stream of found handler symbols with the Compilation object.
            // The Compilation object is needed in the execution phase to resolve types.
            IncrementalValueProvider<(Compilation Compilation, ImmutableArray<INamedTypeSymbol> HandlerSymbols)> compilationAndHandlers
                = context.CompilationProvider.Combine(handlerClassSymbols.Collect());

            // STEP 3: Register the final execution step (Execute method) 
            // to be called with the combined compilation and handler symbols.
            context.RegisterSourceOutput(compilationAndHandlers, Execute);
        }

        /// <summary>
        /// Semantic filter executed only for nodes passing the predicate.
        /// Returns the INamedTypeSymbol if it represents a concrete class, otherwise null.
        /// </summary>
        private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context, CancellationToken cancellationToken)
        {
            var classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
            // Get the semantic symbol representing the class definition
            var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax, cancellationToken) as INamedTypeSymbol;

            // Ignore interfaces, structs, enums, delegates, abstract classes, static classes, or if symbol is null
            if (classSymbol == null || classSymbol.TypeKind != TypeKind.Class || classSymbol.IsAbstract || classSymbol.IsStatic)
            {
                return null;
            }
            // Return the symbol for the concrete class
            return classSymbol;
        }

        /// <summary>
        /// Main generation method, executed with the compilation and collected handler symbols.
        /// </summary>
        private static void Execute(SourceProductionContext context, (Compilation Compilation, ImmutableArray<INamedTypeSymbol> HandlerSymbols) source)
        {
            var (compilation, handlerSymbols) = source; // Deconstruct the tuple
            if (handlerSymbols.IsDefaultOrEmpty) return; // Exit if no potential handlers found

            // --- Get required base symbols from the compilation context ---
            // These are needed for analysis and comparison later.
            INamedTypeSymbol? unitSymbol = compilation.GetTypeByMetadataName(UnitTypeFullName);
            INamedTypeSymbol? queryHandlerDef = compilation.GetTypeByMetadataName(QueryHandlerInterfaceFullName);
            INamedTypeSymbol? commandHandlerDef = compilation.GetTypeByMetadataName(CommandHandlerInterfaceFullName);
            INamedTypeSymbol? commandHandlerWithResponseDef = compilation.GetTypeByMetadataName(CommandHandlerWithResponseInterfaceFullName);
            INamedTypeSymbol? requestHandlerDef = compilation.GetTypeByMetadataName(RequestHandlerInterfaceFullName);
            INamedTypeSymbol? requestHandlerWithoutResponseDef = compilation.GetTypeByMetadataName(RequestHandlerWithoutResponseInterfaceFullName);
            INamedTypeSymbol? streamRequestHandlerDef = compilation.GetTypeByMetadataName(StreamRequestHandlerInterfaceFullName);
            INamedTypeSymbol? generatedDispatcherInterfaceSymbol = compilation.GetTypeByMetadataName(GeneratedDispatcherInterfaceFullName);

            // --- Crucial Check: Ensure all base types/interfaces are resolvable ---
            // If any of these are null, it likely means the consuming project is not referencing
            // the KyrolusSous.Mediator.Abstractions library correctly. Report an error.
            if (unitSymbol == null || queryHandlerDef == null || commandHandlerDef == null || commandHandlerWithResponseDef == null || requestHandlerDef == null || requestHandlerWithoutResponseDef == null || streamRequestHandlerDef == null || generatedDispatcherInterfaceSymbol == null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        id: "SMG001",
                        title: "KyrolusSous.Mediator base types/interfaces not found",
                        messageFormat: "Could not find required KyrolusSous.Mediator types ({0}). Ensure the project references the KyrolusSous.Mediator.Abstractions library correctly.",
                        category: "KyrolusSous.Mediator.Generator",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    Location.None,
                    string.Join(", ", new[] { // List the types being checked
                        UnitTypeFullName, QueryHandlerInterfaceFullName, CommandHandlerInterfaceFullName,
                        CommandHandlerWithResponseInterfaceFullName, RequestHandlerInterfaceFullName,
                        RequestHandlerWithoutResponseInterfaceFullName, StreamRequestHandlerInterfaceFullName,
                        GeneratedDispatcherInterfaceFullName
                    }.Where(s => compilation.GetTypeByMetadataName(s) == null)) // Only show missing ones
                ));
                return; // Stop generation if base types are missing
            }

            // --- Analyze handler symbols and collect detailed information ---
            var handlerInfos = new List<HandlerInfo>();
            var openGenericHandlers = new List<OpenGenericHandlerInfo>();
            // HashSet to store unique namespaces required for 'using' statements in generated code
            var namespaces = new HashSet<string>
            {
                "System", "System.Threading", "System.Threading.Tasks",
                "System.Collections.Generic", "System.Runtime.CompilerServices", "Microsoft.Extensions.DependencyInjection",
                "KyrolusSous.Mediator.Abstractions.Interfaces", // Namespace for IKyrolusCommand, IKyrolusQuery etc.
                "KyrolusSous.Mediator.Generated", // Namespace for the generated static dispatcher
                generatedDispatcherInterfaceSymbol.ContainingNamespace.ToDisplayString() // Namespace for IGeneratedDispatcher (e.g., KyrolusMediator)
            };

            // Iterate through the concrete class symbols identified in the Initialize pipeline
            var handlerDefinitions = new HandlerInterfaceDefinitions(
                unitSymbol,
                queryHandlerDef,
                commandHandlerDef,
                commandHandlerWithResponseDef,
                requestHandlerDef,
                requestHandlerWithoutResponseDef,
                streamRequestHandlerDef);

            foreach (var handlerSymbol in handlerSymbols)
            {
                context.CancellationToken.ThrowIfCancellationRequested(); // Check for cancellation

                if (handlerSymbol.IsGenericType && handlerSymbol.TypeParameters.Length > 0)
                {
                    foreach (var openGeneric in TryGetOpenGenericHandlerRegistrations(handlerSymbol, handlerDefinitions))
                    {
                        openGenericHandlers.Add(openGeneric);
                    }
                    continue;
                }

                // Call helper method to analyze the symbol and extract handler details
                var handlerInfo = TryGetHandlerInfo(handlerSymbol, handlerDefinitions);
                if (handlerInfo != null)
                {
                    handlerInfos.Add(handlerInfo);
                    // Collect namespaces from the types involved for 'using' statements
                    CollectNamespaces(handlerInfo.HandlerType, namespaces);
                    CollectNamespaces(handlerInfo.RequestType, namespaces);
                    CollectNamespaces(handlerInfo.ResponseType, namespaces);
                }
                // Optional: Add diagnostic warning if a class looks like a handler but doesn't match perfectly?
            }

            // --- Generate the source code files if any valid handlers were found ---
            if (handlerInfos.Count > 0)
            {
                // 1. Generate the static dispatcher class (contains the core logic)
                string staticDispatcherCode = GenerateStaticDispatcherCode(handlerInfos, unitSymbol, namespaces);
                context.AddSource("KyrolusSous.Mediator.GeneratedDispatcher.g.cs", SourceText.From(staticDispatcherCode, Encoding.UTF8));

                // 2. Generate the class implementing the internal IGeneratedDispatcher interface
                string dispatcherImplCode = GenerateDispatcherImplementation(generatedDispatcherInterfaceSymbol);
                context.AddSource("KyrolusSous.Mediator.GeneratedDispatcherImpl.g.cs", SourceText.From(dispatcherImplCode, Encoding.UTF8));

                // 3. Generate the DI extension method to register the implementation
                string diExtensionCode = GenerateDIRegistration(generatedDispatcherInterfaceSymbol);
                context.AddSource("KyrolusSous.Mediator.GeneratedDIExtensions.g.cs", SourceText.From(diExtensionCode, Encoding.UTF8));

                // 4. Generate the DI extension method for Handler Registration ****
                string handlersDiExtensionCode = GenerateHandlerRegistrationMethod(handlerInfos, openGenericHandlers, namespaces);
                context.AddSource("KyrolusSous.Mediator.GeneratedHandlersDIExtensions.g.cs", SourceText.From(handlersDiExtensionCode, Encoding.UTF8));
            }
        }

        // --- Helper Record ---
        /// <summary>Helper class to store extracted information about a specific handler.</summary>
        private sealed class HandlerInfo
        {
            public HandlerInfo(INamedTypeSymbol handlerType, INamedTypeSymbol requestType, ITypeSymbol responseType, string interfaceFullName, bool isStream)
            {
                HandlerType = handlerType;
                RequestType = requestType;
                ResponseType = responseType;
                InterfaceFullName = interfaceFullName;
                IsStream = isStream;
            }

            public INamedTypeSymbol HandlerType { get; }
            public INamedTypeSymbol RequestType { get; }
            public ITypeSymbol ResponseType { get; }
            public string InterfaceFullName { get; }
            public bool IsStream { get; }
        }

        private sealed class OpenGenericHandlerInfo
        {
            public OpenGenericHandlerInfo(INamedTypeSymbol handlerType, INamedTypeSymbol interfaceType)
            {
                HandlerType = handlerType;
                InterfaceType = interfaceType;
            }

            public INamedTypeSymbol HandlerType { get; }
            public INamedTypeSymbol InterfaceType { get; }
        }

        private sealed class HandlerInterfaceDefinitions
        {
            public HandlerInterfaceDefinitions(
                INamedTypeSymbol unitSymbol,
                INamedTypeSymbol queryHandlerDef,
                INamedTypeSymbol commandHandlerDef,
                INamedTypeSymbol commandHandlerWithResponseDef,
                INamedTypeSymbol requestHandlerDef,
                INamedTypeSymbol requestHandlerWithoutResponseDef,
                INamedTypeSymbol streamRequestHandlerDef)
            {
                UnitSymbol = unitSymbol;
                QueryHandlerDef = queryHandlerDef;
                CommandHandlerDef = commandHandlerDef;
                CommandHandlerWithResponseDef = commandHandlerWithResponseDef;
                RequestHandlerDef = requestHandlerDef;
                RequestHandlerWithoutResponseDef = requestHandlerWithoutResponseDef;
                StreamRequestHandlerDef = streamRequestHandlerDef;
            }

            public INamedTypeSymbol UnitSymbol { get; }
            public INamedTypeSymbol QueryHandlerDef { get; }
            public INamedTypeSymbol CommandHandlerDef { get; }
            public INamedTypeSymbol CommandHandlerWithResponseDef { get; }
            public INamedTypeSymbol RequestHandlerDef { get; }
            public INamedTypeSymbol RequestHandlerWithoutResponseDef { get; }
            public INamedTypeSymbol StreamRequestHandlerDef { get; }
        }

        // --- Helper Methods ---

        /// <summary>
        /// Analyzes a class symbol to determine if it implements one of the KyrolusMediator handler interfaces
        /// and extracts the request and response types.
        /// </summary>
        private static HandlerInfo? TryGetHandlerInfo(INamedTypeSymbol handlerSymbol, HandlerInterfaceDefinitions defs)
        {
            // Iterate through all interfaces (including inherited ones)
            foreach (var iface in handlerSymbol.AllInterfaces)
            {
                // Ensure it's a constructed generic type (e.g., IKyrolusCommandHandler<MyCommand, Unit>)
                if (!iface.IsGenericType || iface.ConstructedFrom == null) continue;

                if (!TryMatchHandlerInterface(iface, defs, out var reqType, out var resType, out var isStream))
                {
                    continue;
                }
                string ifaceName = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat); // Get full name like IKyrolusCommandHandler<NS.Req, NS.Resp>

                // If a match was found and types were extracted successfully
                if (reqType != null && resType != null)
                {
                    return new HandlerInfo(handlerSymbol, reqType, resType, ifaceName, isStream);
                }
            }
            return null; // Not a recognized handler interface implementation
        }

        private static bool TryMatchHandlerInterface(
            INamedTypeSymbol iface,
            HandlerInterfaceDefinitions defs,
            out INamedTypeSymbol? reqType,
            out ITypeSymbol? resType,
            out bool isStream)
        {
            reqType = null;
            resType = null;
            isStream = false;

            var originalDef = iface.OriginalDefinition; // Get the unbound generic definition (e.g., IKyrolusCommandHandler<,>)
            if (iface.TypeArguments.Length == 2)
            {
                if (SymbolEqualityComparer.Default.Equals(originalDef, defs.QueryHandlerDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.CommandHandlerWithResponseDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.RequestHandlerDef))
                {
                    reqType = iface.TypeArguments[0] as INamedTypeSymbol;
                    resType = iface.TypeArguments[1];
                    return true;
                }
                if (SymbolEqualityComparer.Default.Equals(originalDef, defs.StreamRequestHandlerDef))
                {
                    reqType = iface.TypeArguments[0] as INamedTypeSymbol;
                    resType = iface.TypeArguments[1];
                    isStream = true;
                    return true;
                }
                return false;
            }

            if (iface.TypeArguments.Length == 1 &&
                (SymbolEqualityComparer.Default.Equals(originalDef, defs.CommandHandlerDef) ||
                 SymbolEqualityComparer.Default.Equals(originalDef, defs.RequestHandlerWithoutResponseDef)))
            {
                reqType = iface.TypeArguments[0] as INamedTypeSymbol;
                resType = defs.UnitSymbol;
                return true;
            }

            return false;
        }

        private static IEnumerable<OpenGenericHandlerInfo> TryGetOpenGenericHandlerRegistrations(
            INamedTypeSymbol handlerSymbol,
            HandlerInterfaceDefinitions defs)
        {
            foreach (var iface in handlerSymbol.AllInterfaces)
            {
                if (!iface.IsGenericType || iface.ConstructedFrom is null) continue;

                var originalDef = iface.OriginalDefinition;
                if (SymbolEqualityComparer.Default.Equals(originalDef, defs.QueryHandlerDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.CommandHandlerDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.CommandHandlerWithResponseDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.RequestHandlerDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.RequestHandlerWithoutResponseDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.StreamRequestHandlerDef))
                {
                    yield return new OpenGenericHandlerInfo(handlerSymbol.OriginalDefinition, originalDef);
                }
            }
        }

        /// <summary>
        /// Generates the source code for the static GeneratedMediatorDispatcher class.
        /// </summary>
        private static string GenerateStaticDispatcherCode(List<HandlerInfo> handlerInfos, INamedTypeSymbol unitSymbol, HashSet<string> namespaces)
        {
            var sb = new StringBuilder();
            // --- File Header ---
            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine(NullableEnable);
            sb.AppendLine();

            // --- Using Statements ---
            foreach (var ns in namespaces.OrderBy(n => n)) sb.AppendLine($"using {ns};");
            sb.AppendLine();

            // --- Namespace and Class Definition ---
            sb.AppendLine("namespace KyrolusSous.Mediator.Generated");
            sb.AppendLine(OpenBrace);
            sb.AppendLine(CompilerGeneratedAttribute);
            sb.AppendLine("    internal static class GeneratedMediatorDispatcher");
            sb.AppendLine(Indent4OpenBrace);

            // --- Dictionaries ---
            var streamHandlerCount = handlerInfos.Count(info => info.IsStream);
            sb.AppendLine($"        private static readonly Dictionary<Type, Func<object, IServiceProvider, CancellationToken, Task>> s_commandDispatchers = new({handlerInfos.Count});");
            sb.AppendLine($"        private static readonly Dictionary<Type, Func<object, IServiceProvider, CancellationToken, Task<object>>> s_requestDispatchers = new({handlerInfos.Count});");
            sb.AppendLine($"        private static readonly Dictionary<Type, Func<object, IServiceProvider, CancellationToken, IAsyncEnumerable<object>>> s_streamDispatchers = new({streamHandlerCount});");
            sb.AppendLine();

            // --- Static Constructor ---
            sb.AppendLine("        static GeneratedMediatorDispatcher()");
            sb.AppendLine(Indent8OpenBrace);

            // --- Populate Dictionaries ---
            foreach (var info in handlerInfos)
            {
                string hFullName = info.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string rFullName = info.RequestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string iFullName = info.InterfaceFullName;
                bool isCmd = info.ResponseType.Equals(unitSymbol, SymbolEqualityComparer.Default);

                sb.AppendLine($"            // Handler: {hFullName} Request: {rFullName}");
                if (info.IsStream)
                {
                    sb.AppendLine($"            s_streamDispatchers[typeof({rFullName})] = (req, sp, ct) =>");
                    sb.AppendLine($"            {{ var handler = ({iFullName})sp.GetRequiredService<{hFullName}>(); return CastStreamToObject(handler.Handle(({rFullName})req, ct), ct); }};");
                }
                else if (isCmd)
                {
                    sb.AppendLine($"            s_commandDispatchers[typeof({rFullName})] = async (req, sp, ct) =>");
                    sb.AppendLine($"            {{ var handler = ({iFullName})sp.GetRequiredService<{hFullName}>(); await handler.Handle(({rFullName})req, ct); }};");
                }
                else
                {
                    sb.AppendLine($"            s_requestDispatchers[typeof({rFullName})] = async (req, sp, ct) =>");
                    sb.AppendLine($"            {{ var handler = ({iFullName})sp.GetRequiredService<{hFullName}>(); var result = await handler.Handle(({rFullName})req, ct); return (object)result!; }};");
                }
                sb.AppendLine();
            }
            sb.AppendLine(Indent8CloseBrace); // End static constructor
            sb.AppendLine();

            // --- Dispatch Methods ---
            GenerateDispatchMethod(sb, isCommand: true, unitSymbol);
            GenerateDispatchMethod(sb, isCommand: false, unitSymbol);
            GenerateStreamDispatchMethod(sb);

            sb.AppendLine(Indent4CloseBrace); // End class
            sb.AppendLine(CloseBrace); // End namespace
            return sb.ToString();
        }

        /// <summary>
        /// Generates the implementation class for the internal IGeneratedDispatcher interface.
        /// </summary>
        private static string GenerateDispatcherImplementation(INamedTypeSymbol generatedDispatcherInterfaceSymbol)
        {
            var sb = new StringBuilder();
            string interfaceFullName = generatedDispatcherInterfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string interfaceNamespace = generatedDispatcherInterfaceSymbol.ContainingNamespace.ToDisplayString();

            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine(NullableEnable);
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine($"using {interfaceNamespace}; // Namespace of IGeneratedDispatcher");
            sb.AppendLine();
            sb.AppendLine("namespace KyrolusSous.Mediator.Generated"); // Keep in Generated namespace
            sb.AppendLine(OpenBrace);
            sb.AppendLine("    /// <summary>Implements the internal dispatcher interface by delegating to the static dispatcher.</summary>");
            sb.AppendLine(CompilerGeneratedAttribute);
            sb.AppendLine($"    internal sealed class GeneratedDispatcher : {interfaceFullName}");
            sb.AppendLine(Indent4OpenBrace);
            sb.AppendLine("        public Task<TResponse> DispatchRequestAsync<TResponse>(object request, IServiceProvider sp, CancellationToken ct)");
            sb.AppendLine("            => GeneratedMediatorDispatcher.DispatchRequestAsync<TResponse>(request, sp, ct);");
            sb.AppendLine();
            sb.AppendLine("        public Task DispatchCommandAsync(object command, IServiceProvider sp, CancellationToken ct)");
            sb.AppendLine("            => GeneratedMediatorDispatcher.DispatchCommandAsync(command, sp, ct);");
            sb.AppendLine();
            sb.AppendLine("        public IAsyncEnumerable<TResponse> DispatchStreamAsync<TResponse>(object request, IServiceProvider sp, CancellationToken ct)");
            sb.AppendLine("            => GeneratedMediatorDispatcher.DispatchStreamAsync<TResponse>(request, sp, ct);");
            sb.AppendLine(Indent4CloseBrace);
            sb.AppendLine(CloseBrace);
            return sb.ToString();
        }

        /// <summary>
        /// Generates the DI extension method for registering the IGeneratedDispatcher implementation.
        /// </summary>
        private static string GenerateDIRegistration(INamedTypeSymbol generatedDispatcherInterfaceSymbol)
        {
            var sb = new StringBuilder();
            string interfaceFullName = generatedDispatcherInterfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string implementationFullName = "KyrolusSous.Mediator.Generated.GeneratedDispatcher"; // Full name of the implementation class
            string interfaceNamespace = generatedDispatcherInterfaceSymbol.ContainingNamespace.ToDisplayString();

            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine(NullableEnable);
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
            sb.AppendLine($"using {interfaceNamespace}; // Namespace of IGeneratedDispatcher");
            sb.AppendLine($"using KyrolusSous.Mediator.Generated; // Namespace of GeneratedDispatcher implementation");
            sb.AppendLine();
            // Put extensions in a relevant namespace, e.g., Microsoft.Extensions.DependencyInjection for discoverability
            sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
            sb.AppendLine(OpenBrace);
            sb.AppendLine("    /// <summary>Extension methods for registering generated KyrolusSous.Mediator components.</summary>");
            sb.AppendLine(CompilerGeneratedAttribute);
            sb.AppendLine("    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]"); // Hide from intellisense? Optional
            sb.AppendLine("    public static class KyrolusMediatorGeneratedDIExtensions");
            sb.AppendLine(Indent4OpenBrace);
            sb.AppendLine("        /// <summary>Registers the generated dispatcher implementation.</summary>");
            sb.AppendLine("        /// <remarks>Call this after registering handlers and before resolving IKyrolusMediatorSender.</remarks>");
            sb.AppendLine("        public static IServiceCollection AddKyrolusMediatorGeneratedDispatcher(this IServiceCollection services)");
            sb.AppendLine(Indent8OpenBrace);
            // Replace any existing dispatcher (e.g., reflection-based) with the generated one
            sb.AppendLine($"            services.Replace(ServiceDescriptor.Singleton<{interfaceFullName}, {implementationFullName}>());");
            sb.AppendLine("            return services;");
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine(Indent4CloseBrace);
            sb.AppendLine(CloseBrace);
            return sb.ToString();
        }
        // **** NEW HELPER METHOD ****
        /// <summary>
        /// Generates the DI extension method for registering all discovered concrete handlers.
        /// </summary>
        private static string GenerateHandlerRegistrationMethod(List<HandlerInfo> handlerInfos, List<OpenGenericHandlerInfo> openGenericHandlers, HashSet<string> namespaces)
        {
            var sb = new StringBuilder();
            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine(NullableEnable);
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
            // Add using statements for handler namespaces collected previously
            foreach (var ns in namespaces.Where(n => !n.StartsWith("System") && !n.StartsWith("Microsoft") && !n.StartsWith("KyrolusSous.Mediator")) // Avoid redundant usings
                                        .OrderBy(n => n))
            {
                sb.AppendLine($"using {ns};");
            }
            sb.AppendLine();
            // Place in a common namespace for extensions
            sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
            sb.AppendLine(OpenBrace);
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Extension methods for registering KyrolusSous.Mediator handlers discovered by the generator.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine(CompilerGeneratedAttribute);
            sb.AppendLine("    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine("    public static class KyrolusMediatorGeneratedHandlersDIExtensions");
            sb.AppendLine(Indent4OpenBrace);
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Registers all concrete Command and Query handlers discovered by the KyrolusSous.Mediator.Generator.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static IServiceCollection AddKyrolusMediatorHandlers(this IServiceCollection services)");
            sb.AppendLine(Indent8OpenBrace);

            // Loop through all discovered handlers and add registration lines
            foreach (var info in handlerInfos)
            {
                string handlerFullName = info.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                // Register the concrete handler type. Transient lifetime is typical for handlers.
                sb.AppendLine($"            services.TryAddTransient<{handlerFullName}>();");

                // --- Optional: Registering against specific interfaces ---
                // You might also want to register the handler against its specific closed-generic interface
                // although resolving the concrete type directly is often sufficient if dependencies ask for the concrete type.
                // If you need to resolve handlers via their specific interface (e.g., IEnumerable<IKyrolusQueryHandler<...>>), uncomment below.
                // string interfaceFullName = info.InterfaceFullName; 
                // sb.AppendLine($"            services.TryAddTransient<{interfaceFullName}, {handlerFullName}>();");
                // --- End Optional ---
            }

            sb.AppendLine();
            // Register open generic handlers
            foreach (var info in openGenericHandlers)
            {
                string interfaceType = GetOpenGenericTypeOf(info.InterfaceType);
                string handlerType = GetOpenGenericTypeOf(info.HandlerType);
                sb.AppendLine($"            services.TryAddTransient(typeof({interfaceType}), typeof({handlerType}));");
            }
            sb.AppendLine();
            sb.AppendLine("            return services;");
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine(Indent4CloseBrace);
            sb.AppendLine(CloseBrace);
            return sb.ToString();
        }

        private static string GetOpenGenericTypeOf(INamedTypeSymbol symbol)
        {
            string ns = symbol.ContainingNamespace.ToDisplayString();
            string name = symbol.Name;
            int arity = symbol.Arity;
            string typeParams = arity == 0 ? string.Empty : $"<{new string(',', arity - 1)}>";
            return $"global::{ns}.{name}{typeParams}";
        }
        /// <summary>
        /// Helper method to generate the body of the static dispatch methods.
        /// </summary>
        private static void GenerateDispatchMethod(StringBuilder sb, bool isCommand, INamedTypeSymbol unitSymbol)
        {
            string dictionaryName = isCommand ? "s_commandDispatchers" : "s_requestDispatchers";
            string inputParamName = isCommand ? "command" : "request";
            string returnType = isCommand ? "Task" : "Task<TResponse>";
            string methodName = isCommand ? "DispatchCommandAsync" : "DispatchRequestAsync";
            string genericParam = isCommand ? "" : "<TResponse>";
            string exceptionInterfaceText = isCommand ? "IKyrolusCommandHandler<...>" : "IKyrolusQueryHandler<...> or IKyrolusCommandHandler<..., TResponse>";
            string taskResultVar = "result";
            string awaitPrefix = isCommand ? "" : "async ";
            string inputParameterType = "object";
            string unitFullName = unitSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string localRequestVarName = isCommand ? "commandType" : "requestType";

            sb.AppendLine($"        /// <summary>Dispatches a {(isCommand ? "command (Task return)" : "request (TResponse return)")}.</summary>");
            sb.AppendLine($"        public static {awaitPrefix}{returnType} {methodName}{genericParam}({inputParameterType} {inputParamName}, IServiceProvider serviceProvider, CancellationToken cancellationToken)");
            sb.AppendLine(Indent8OpenBrace);
            sb.AppendLine($"            var {localRequestVarName} = {inputParamName}.GetType();"); // Get runtime type
            sb.AppendLine();
            sb.AppendLine($"            // Try finding the handler in the primary dictionary");
            sb.AppendLine($"            if ({dictionaryName}.TryGetValue({localRequestVarName}, out var handlerFunc))");
            sb.AppendLine(Indent12OpenBrace);
            if (isCommand)
            { sb.AppendLine($"                return handlerFunc({inputParamName}, serviceProvider, cancellationToken);"); }
            else
            {
                sb.AppendLine($"                var {taskResultVar} = await handlerFunc({inputParamName}, serviceProvider, cancellationToken);");
                sb.AppendLine($"                // Check for null return from handler when TResponse is a non-nullable value type");
                sb.AppendLine($"                if ({taskResultVar} == null && default(TResponse) != null)");
                sb.AppendLine(Indent16OpenBrace);
                sb.AppendLine($"                   throw new InvalidCastException($\"[KyrolusMediator] Handler for {{{localRequestVarName}.FullName}} returned null, but expected non-nullable {{typeof(TResponse).FullName}}.\");");
                sb.AppendLine(Indent16CloseBrace);
                sb.AppendLine($"                return (TResponse){taskResultVar}!;"); // Cast/unbox result
            }
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
            sb.AppendLine($"            // Fallback logic if not found in the primary dictionary");
            if (isCommand)
            {
                // If DispatchCommandAsync called for something that returns Unit but was registered as Request
                sb.AppendLine($"            if (s_requestDispatchers.TryGetValue({localRequestVarName}, out var reqFunc))");
                sb.AppendLine(Indent12OpenBrace);
                sb.AppendLine($"                 // Found in request dispatcher (likely returns Unit); execute and return Task.");
                sb.AppendLine($"                 return reqFunc({inputParamName}, serviceProvider, cancellationToken); // Return Task<object> as Task");
                sb.AppendLine(Indent12CloseBrace);
            }
            else
            {
                // If DispatchRequestAsync<Unit> called for something registered as Command
                sb.AppendLine($"            if (typeof(TResponse) == typeof({unitFullName}) && s_commandDispatchers.TryGetValue({localRequestVarName}, out var cmdFunc))");
                sb.AppendLine(Indent12OpenBrace);
                sb.AppendLine($"                // Found in command dispatcher and expecting Unit; execute and return Unit.");
                sb.AppendLine($"                await cmdFunc({inputParamName}, serviceProvider, cancellationToken);");
                sb.AppendLine($"                return (TResponse)(object){unitFullName}.Value; // Box Unit and cast to TResponse (Unit)");
                sb.AppendLine(Indent12CloseBrace);
            }
            sb.AppendLine();
            AppendOpenGenericDispatchFallback(sb, isCommand, inputParamName, localRequestVarName);
            sb.AppendLine();
            sb.AppendLine($"            // No handler found after primary lookup and fallback.");
            // Generate the exception message string carefully
            sb.Append($"            throw new InvalidOperationException($\"[KyrolusMediator] No handler registered for {{{localRequestVarName}.FullName}}");
            if (!isCommand) { sb.Append($" returning {{typeof(TResponse).FullName}}"); }
            sb.Append($". Ensure the handler class is concrete, public, implements {exceptionInterfaceText}, and is registered in the dependency injection container.\");");
            sb.AppendLine(); // Add the semicolon and newline

            sb.AppendLine(Indent8CloseBrace); // End method
            sb.AppendLine();
        }

        private static void GenerateStreamDispatchMethod(StringBuilder sb)
        {
            sb.AppendLine("        /// <summary>Dispatches a streaming request.</summary>");
            sb.AppendLine("        public static IAsyncEnumerable<TResponse> DispatchStreamAsync<TResponse>(object request, IServiceProvider serviceProvider, CancellationToken cancellationToken)");
            sb.AppendLine(Indent8OpenBrace);
            sb.AppendLine("            var requestType = request.GetType();");
            sb.AppendLine();
            sb.AppendLine("            if (s_streamDispatchers.TryGetValue(requestType, out var handlerFunc))");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                return CastStreamFromObject<TResponse>(handlerFunc(request, serviceProvider, cancellationToken), requestType, cancellationToken);");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
            sb.AppendLine("            // Try resolving open generic stream handlers registered in DI.");
            sb.AppendLine("            var openHandlerType = typeof(IKyrolusStreamRequestHandler<,>).MakeGenericType(requestType, typeof(TResponse));");
            sb.AppendLine("            var openHandler = serviceProvider.GetService(openHandlerType);");
            sb.AppendLine("            if (openHandler is not null)");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                var method = openHandlerType.GetMethod(\"Handle\", new[] { requestType, typeof(CancellationToken) });");
            sb.AppendLine("                if (method is null) throw new InvalidOperationException($\"[KyrolusMediator] Could not find Handle(...) on {openHandlerType.FullName}.\");");
            sb.AppendLine("                var stream = (IAsyncEnumerable<TResponse>)method.Invoke(openHandler, new object[] { request, cancellationToken })!;");
            sb.AppendLine("                return stream;");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
            sb.AppendLine("            throw new InvalidOperationException($\"[KyrolusMediator] No stream handler registered for {requestType.FullName}. Ensure the handler class is concrete, public, implements IKyrolusStreamRequestHandler<..., ...>, and is registered in the dependency injection container.\");");
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine();

            sb.AppendLine("        private static async IAsyncEnumerable<object> CastStreamToObject<T>(IAsyncEnumerable<T> source, [EnumeratorCancellation] CancellationToken cancellationToken)");
            sb.AppendLine(Indent8OpenBrace);
            sb.AppendLine("            await foreach (var item in source.WithCancellation(cancellationToken).ConfigureAwait(false))");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                yield return item!;");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine();

            sb.AppendLine("        private static async IAsyncEnumerable<TResponse> CastStreamFromObject<TResponse>(IAsyncEnumerable<object> source, Type requestType, [EnumeratorCancellation] CancellationToken cancellationToken)");
            sb.AppendLine(Indent8OpenBrace);
            sb.AppendLine("            await foreach (var item in source.WithCancellation(cancellationToken).ConfigureAwait(false))");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                if (item is null)");
            sb.AppendLine(Indent16OpenBrace);
            sb.AppendLine("                    if (default(TResponse) is not null)");
            sb.AppendLine(Indent16OpenBrace);
            sb.AppendLine("                        throw new InvalidCastException($\"[KyrolusMediator] Stream handler for {requestType.FullName} returned null, but expected non-nullable {typeof(TResponse).FullName}.\");");
            sb.AppendLine(Indent16CloseBrace);
            sb.AppendLine();
            sb.AppendLine("                    yield return (TResponse)(object)default!;");
            sb.AppendLine("                    continue;");
            sb.AppendLine(Indent16CloseBrace);
            sb.AppendLine();
            sb.AppendLine("                if (item is TResponse typed)");
            sb.AppendLine(Indent16OpenBrace);
            sb.AppendLine("                    yield return typed;");
            sb.AppendLine("                    continue;");
            sb.AppendLine(Indent16CloseBrace);
            sb.AppendLine();
            sb.AppendLine("                throw new InvalidCastException($\"[KyrolusMediator] Stream handler for {requestType.FullName} returned item of type {item.GetType().FullName}, expected {typeof(TResponse).FullName}.\");");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine();
        }

        private static void AppendOpenGenericDispatchFallback(StringBuilder sb, bool isCommand, string inputParamName, string localRequestVarName)
        {
            sb.AppendLine("            // Try resolving open generic handlers registered in DI.");
            if (isCommand)
            {
                sb.AppendLine($"            var commandHandlerType = typeof(IKyrolusCommandHandler<>).MakeGenericType({localRequestVarName});");
                sb.AppendLine("            var commandHandler = serviceProvider.GetService(commandHandlerType);");
                sb.AppendLine("            if (commandHandler is not null)");
                sb.AppendLine(Indent12OpenBrace);
                sb.AppendLine($"                var method = commandHandlerType.GetMethod(\"Handle\", new[] {{ {localRequestVarName}, typeof(CancellationToken) }});");
                sb.AppendLine("                if (method is null) throw new InvalidOperationException($\"[KyrolusMediator] Could not find Handle(...) on {commandHandlerType.FullName}.\");");
                sb.AppendLine($"                var task = (Task)method.Invoke(commandHandler, new object[] {{ {inputParamName}, cancellationToken }})!;");
                sb.AppendLine("                return task;");
                sb.AppendLine(Indent12CloseBrace);
                return;
            }

            sb.AppendLine("            Type? openGenericHandlerType = null;");
            sb.AppendLine($"            if ({inputParamName} is IKyrolusCommandBase)");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine($"                openGenericHandlerType = typeof(IKyrolusCommandHandler<,>).MakeGenericType({localRequestVarName}, typeof(TResponse));");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine($"            else if ({inputParamName} is IKyrolusQueryBase)");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine($"                openGenericHandlerType = typeof(IKyrolusQueryHandler<,>).MakeGenericType({localRequestVarName}, typeof(TResponse));");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine("            else");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine($"                openGenericHandlerType = typeof(IKyrolusRequestHandler<,>).MakeGenericType({localRequestVarName}, typeof(TResponse));");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
            sb.AppendLine("            var openHandler = openGenericHandlerType is null ? null : serviceProvider.GetService(openGenericHandlerType);");
            sb.AppendLine("            if (openHandler is not null)");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                var method = openGenericHandlerType!.GetMethod(\"Handle\", new[] { " + localRequestVarName + ", typeof(CancellationToken) });");
            sb.AppendLine("                if (method is null) throw new InvalidOperationException($\"[KyrolusMediator] Could not find Handle(...) on {openGenericHandlerType.FullName}.\");");
            sb.AppendLine($"                var task = (Task<TResponse>)method.Invoke(openHandler, new object[] {{ {inputParamName}, cancellationToken }})!;");
            sb.AppendLine("                return await task;");
            sb.AppendLine(Indent12CloseBrace);
        }

        /// <summary>
        /// Recursively collects namespaces from type symbols for 'using' statements.
        /// </summary>
        private static void CollectNamespaces(ITypeSymbol typeSymbol, HashSet<string> namespaces)
        {
            if (typeSymbol is null)
            {
                return;
            }

            if (typeSymbol is INamedTypeSymbol namedType)
            {
                AddNamespace(namedType, namespaces);
                foreach (var arg in namedType.TypeArguments)
                {
                    CollectNamespaces(arg, namespaces);
                }

                if (namedType.ContainingType is not null)
                {
                    CollectNamespaces(namedType.ContainingType, namespaces);
                }

                return;
            }

            if (typeSymbol is IArrayTypeSymbol arrayType)
            {
                CollectNamespaces(arrayType.ElementType, namespaces);
                return;
            }

            AddNamespace(typeSymbol, namespaces);
        }

        private static void AddNamespace(ITypeSymbol typeSymbol, HashSet<string> namespaces)
        {
            if (typeSymbol.ContainingNamespace is not null && !typeSymbol.ContainingNamespace.IsGlobalNamespace)
            {
                namespaces.Add(typeSymbol.ContainingNamespace.ToDisplayString());
            }
        }
    } // End Generator class
} // End namespace
