global using KyrolusSous.CQRS.Abstractions.Interfaces;
global using KyrolusSous.Repositories.Marten.Abstractions.Interfaces;
global using KyrolusSous.Repositories.Marten.Abstractions.Records;
global using System.Linq.Expressions;
global using System.Reflection;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using KyrolusSous.Mediator.Abstractions.Interfaces;
global using Marten;
