// MediatorGenerator.cs
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

// Define the namespace for the generator project
namespace KyrolusSous.Mediator.Generator
{
    [Generator] // Mark this class as a Source Generator
    public class MediatorGenerator : IIncrementalGenerator
    {
        private const string AutoGeneratedHeader = "// <auto-generated/>";
        private const string NullableEnable = "#nullable enable";
        private const string CompilerGeneratedAttribute = "    [System.Runtime.CompilerServices.CompilerGenerated]";
        private const string OpenBrace = "{";
        private const string CloseBrace = "}";
        private const string Indent4OpenBrace = "    {";
        private const string Indent4CloseBrace = "    }";
        private const string Indent8OpenBrace = "        {";
        private const string Indent8CloseBrace = "        }";
        private const string Indent12OpenBrace = "            {";
        private const string Indent12CloseBrace = "            }";
        private const string Indent16OpenBrace = "                {";
        private const string Indent16CloseBrace = "                }";

        // --- Constants for necessary fully qualified type names ---
        // These names must exactly match the types defined in the KyrolusSous.Mediator.Abstractions library.
        private const string QueryHandlerInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusQueryHandler`2";
        private const string CommandHandlerInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusCommandHandler`1";
        private const string CommandHandlerWithResponseInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusCommandHandler`2";
        private const string RequestHandlerInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusRequestHandler`2";
        private const string RequestHandlerWithoutResponseInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusRequestHandler`1";
        private const string StreamRequestHandlerInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusStreamRequestHandler`2";
        private const string UnitTypeFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.Unit";
        private const string DispatcherInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusMediatorDispatcher";

        // Lives in the runtime package, not the abstractions, because closing the wrapper types
        // needs the wrapper types - and those stay internal to the runtime. Its presence is what
        // decides whether the AOT wrapper table below can be emitted at all: a project referencing
        // only the abstractions has nothing to hand the table to.
        private const string PipelineWrapperFactoryFullName = "KyrolusSous.Mediator.Runtime.GeneratorIntegration.KyrolusPipelineWrapperFactory";
        private const string PipelineWrapperSourceInterfaceFullName = "KyrolusSous.Mediator.Runtime.GeneratorIntegration.IKyrolusPipelineWrapperSource";
        private const string PipelineWrapperFactoryQualifiedName = "global::" + PipelineWrapperFactoryFullName;
        private const string PipelineWrapperSourceInterfaceQualifiedName = "global::" + PipelineWrapperSourceInterfaceFullName;
        private const string PipelineWrapperSourceImplName = "KyrolusSous.Mediator.Generated.GeneratedPipelineWrapperSource";

        // The four behaviors every pipeline gets. The runtime registers them as open generics and
        // lets the container close them; that is what an ahead-of-time published application cannot
        // do, so the same four are emitted here already closed over each pair.
        private const string PipelineBehaviorInterface = "global::KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusPipelineBehavior";
        private const string StreamPipelineBehaviorInterface = "global::KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusStreamPipelineBehavior";
        private const string RuntimeImplementationsNamespace = "global::KyrolusSous.Mediator.Runtime.Implementations";

        private static readonly string[] BuiltInRequestBehaviors =
        [
            RuntimeImplementationsNamespace + ".KyrolusRequestExceptionProcessorBehavior",
            RuntimeImplementationsNamespace + ".KyrolusRequestPreProcessorBehavior",
            RuntimeImplementationsNamespace + ".KyrolusRequestPostProcessorBehavior"
        ];

        private const string BuiltInStreamBehavior = RuntimeImplementationsNamespace + ".KyrolusStreamPassThroughBehavior";

        private const string ExceptionActionInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusRequestExceptionAction`2";
        private const string ExceptionHandlerInterfaceFullName = "KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusRequestExceptionHandler`3";
        private const string ExceptionDispatchSourceInterfaceFullName = "KyrolusSous.Mediator.Runtime.GeneratorIntegration.IKyrolusRequestExceptionDispatchSource";
        private const string ExceptionDispatchSourceInterfaceQualifiedName = "global::" + ExceptionDispatchSourceInterfaceFullName;
        private const string ExceptionDispatchSourceImplName = "KyrolusSous.Mediator.Generated.GeneratedRequestExceptionDispatchSource";
        private const string ExceptionActionQualifiedName = "global::KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusRequestExceptionAction";
        private const string ExceptionHandlerQualifiedName = "global::KyrolusSous.Mediator.Abstractions.Interfaces.IKyrolusRequestExceptionHandler";
        private const string ExceptionHandlerStateQualifiedName = "global::KyrolusSous.Mediator.Abstractions.Interfaces.KyrolusRequestExceptionHandlerState";

        // The forms written into the generated source. Constants rather than values read off a
        // symbol, so the generation stage needs no Compilation - see the note in Initialize.
        private const string AbstractionsNamespace = "KyrolusSous.Mediator.Abstractions.Interfaces";
        private const string DispatcherInterfaceNamespace = AbstractionsNamespace;
        private const string DispatcherInterfaceQualifiedName = "global::" + DispatcherInterfaceFullName;
        private const string UnitQualifiedName = "global::" + UnitTypeFullName;

        /// <summary>
        /// Called by the compiler to initialize the incremental generator pipeline.
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // STEP 1: For every candidate class, do the semantic analysis here and emit plain data.
            //
            // The transform must return value-equatable data, never symbols. The compiler re-runs
            // this pipeline on every keystroke, and Roslyn decides whether downstream work can be
            // skipped by comparing a stage's output to what it produced last time. Roslyn symbols
            // belong to one Compilation and never compare equal to the symbols of the next one, so
            // returning them makes every stage report "changed" and the caching does nothing.
            // Records of strings and bools compare by value, so an edit that leaves a file's
            // handlers alone leaves this stage's output identical and the generation is skipped.
            IncrementalValuesProvider<ClassHandlerModel> classModels = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                    transform: static (ctx, ct) => GetClassHandlerModel(ctx, ct))
                // Named so a test can ask Roslyn whether this step was recomputed or served from
                // cache, which is the only way to prove the caching above actually works.
                .WithTrackingName(TrackingNames.HandlerModels)
                .Where(static model => model is not null)!;

            // STEP 2: Whether the abstractions are referenced at all, as a bool rather than the
            // Compilation itself.
            //
            // This is the other half of the same rule. Combining with CompilationProvider directly
            // would reintroduce the problem it exists to avoid: the Compilation is a new object on
            // every keystroke, so anything combined with it is permanently "changed". A bool is
            // equatable and stays stable across edits, so it costs nothing.
            // Two bools rather than one, because the two packages answer different questions:
            // the abstractions decide whether anything can be generated at all, the runtime decides
            // whether the AOT wrapper table can be. A ValueTuple of bools is equatable by value, so
            // this stays as cheap to compare as the single bool it replaced.
            IncrementalValueProvider<(bool Abstractions, bool Runtime)> availability = context.CompilationProvider
                .Select(static (compilation, _) => (
                    Abstractions: RequiredTypeNames.All(name => compilation.GetTypeByMetadataName(name) is not null),
                    Runtime: compilation.GetTypeByMetadataName(PipelineWrapperFactoryFullName) is not null
                            && compilation.GetTypeByMetadataName(PipelineWrapperSourceInterfaceFullName) is not null));

            // STEP 3: Register the final execution step with the two small, equatable inputs.
            context.RegisterSourceOutput(
                availability.Combine(classModels.Collect()),
                static (spc, source) => Execute(spc, source.Left, source.Right));
        }

        /// <summary>The types the generated code depends on; all must resolve or nothing is emitted.</summary>
        private static readonly string[] RequiredTypeNames =
        [
            UnitTypeFullName,
            QueryHandlerInterfaceFullName,
            CommandHandlerInterfaceFullName,
            CommandHandlerWithResponseInterfaceFullName,
            RequestHandlerInterfaceFullName,
            RequestHandlerWithoutResponseInterfaceFullName,
            StreamRequestHandlerInterfaceFullName,
            DispatcherInterfaceFullName
        ];

        /// <summary>
        /// Semantic analysis for one candidate class, producing plain data rather than symbols.
        /// </summary>
        /// <remarks>
        /// All of the semantic work happens here, in the per-node stage that Roslyn caches, and the
        /// result is value-equatable. Returning symbols instead would defeat that caching entirely -
        /// see the note in <c>Initialize</c>.
        /// </remarks>
        private static ClassHandlerModel? GetClassHandlerModel(GeneratorSyntaxContext context, CancellationToken cancellationToken)
        {
            var classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
            // Get the semantic symbol representing the class definition
            var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax, cancellationToken) as INamedTypeSymbol;

            // Ignore interfaces, structs, enums, delegates, abstract classes, static classes, or if symbol is null
            if (classSymbol == null || classSymbol.TypeKind != TypeKind.Class || classSymbol.IsAbstract || classSymbol.IsStatic)
                return null;

            var defs = HandlerInterfaceDefinitions.TryResolve(context.SemanticModel.Compilation);
            if (defs is null) return null; // Abstractions not referenced; Execute reports SMG001.

            // Open generic handlers are registered by their open type. They get no dispatch entry:
            // the closed types are only known where they are used.
            if (classSymbol.IsGenericType && classSymbol.TypeParameters.Length > 0)
            {
                var openGenerics = TryGetOpenGenericHandlerRegistrations(classSymbol, defs)
                    .Select(info => new OpenGenericModel(
                        GetOpenGenericTypeOf(info.HandlerType),
                        GetOpenGenericTypeOf(info.InterfaceType)))
                    .ToImmutableArray();

                return openGenerics.IsEmpty
                    ? null
                    : new ClassHandlerModel(default, new EquatableArray<OpenGenericModel>(openGenerics), string.Empty, default, default);
            }

            var namespaces = new SortedSet<string>(StringComparer.Ordinal);
            var handlers = ImmutableArray.CreateBuilder<HandlerModel>();

            // One entry per handler interface: a class handling several messages needs a dispatch
            // entry for each of them.
            foreach (var info in GetHandlerInfos(classSymbol, defs))
            {
                cancellationToken.ThrowIfCancellationRequested();

                handlers.Add(new HandlerModel(
                    info.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    info.RequestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    info.ResponseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    info.InterfaceFullName,
                    info.IsStream));

                // Collect namespaces from the types involved for 'using' statements
                CollectNamespaces(info.HandlerType, namespaces);
                CollectNamespaces(info.RequestType, namespaces);
                CollectNamespaces(info.ResponseType, namespaces);
            }

            // Exception actions and handlers are collected from the same pass. They are not handlers
            // and get no dispatch entry; the generated table only records that the combination
            // exists, so the behavior can resolve it without closing a type at runtime.
            var exceptionActions = ImmutableArray.CreateBuilder<ExceptionActionModel>();
            var exceptionHandlers = ImmutableArray.CreateBuilder<ExceptionHandlerModel>();
            CollectExceptionParticipants(classSymbol, defs, exceptionActions, exceptionHandlers);

            // A class can be an exception action and nothing else, so the handler count alone is not
            // enough to decide the class contributes nothing.
            if (handlers.Count == 0 && exceptionActions.Count == 0 && exceptionHandlers.Count == 0) return null;

            return new ClassHandlerModel(
                new EquatableArray<HandlerModel>(handlers.ToImmutable()),
                default,
                // Joined into one string so the model stays comparable by value.
                string.Join(";", namespaces),
                new EquatableArray<ExceptionActionModel>(exceptionActions.ToImmutable()),
                new EquatableArray<ExceptionHandlerModel>(exceptionHandlers.ToImmutable()));
        }

        /// <summary>
        /// Main generation method, executed with the collected handler models.
        /// </summary>
        private static void Execute(
            SourceProductionContext context,
            (bool Abstractions, bool Runtime) availability,
            ImmutableArray<ClassHandlerModel> classModels)
        {
            // --- Crucial Check: Ensure all base types/interfaces are resolvable ---
            // If any are missing, the consuming project is not referencing the
            // KyrolusSous.Mediator.Abstractions library correctly. Report an error.
            if (!availability.Abstractions)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        id: "SMG001",
                        title: "KyrolusSous.Mediator base types/interfaces not found",
                        messageFormat: "Could not find required KyrolusSous.Mediator types ({0}). Ensure the project references the KyrolusSous.Mediator.Abstractions library correctly.",
                        category: "KyrolusSous.Mediator.Generator",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    Location.None,
                    string.Join(", ", RequiredTypeNames)));
                return; // Stop generation if base types are missing
            }

            if (classModels.IsDefaultOrEmpty) return; // Exit if no handlers found

            var handlerInfos = new List<HandlerModel>();
            var openGenericHandlers = new List<OpenGenericModel>();
            var exceptionActions = new List<ExceptionActionModel>();
            var exceptionHandlers = new List<ExceptionHandlerModel>();
            // HashSet to store unique namespaces required for 'using' statements in generated code
            var namespaces = new HashSet<string>
            {
                "System", "System.Threading", "System.Threading.Tasks",
                "System.Collections.Generic", "System.Runtime.CompilerServices", "Microsoft.Extensions.DependencyInjection",
                "KyrolusSous.Mediator.Abstractions.Interfaces", // Namespace for IKyrolusCommand, IKyrolusQuery etc.
                "KyrolusSous.Mediator.Generated" // Namespace for the generated static dispatcher
            };

            foreach (var model in classModels)
            {
                context.CancellationToken.ThrowIfCancellationRequested(); // Check for cancellation

                handlerInfos.AddRange(model.Handlers.Items);
                openGenericHandlers.AddRange(model.OpenGenerics.Items);
                exceptionActions.AddRange(model.ExceptionActions.Items);
                exceptionHandlers.AddRange(model.ExceptionHandlers.Items);

                if (model.Namespaces.Length > 0)
                {
                    foreach (var ns in model.Namespaces.Split(';'))
                    {
                        namespaces.Add(ns);
                    }
                }
            }

            // --- Generate the source code files if any valid handlers were found ---
            if (handlerInfos.Count > 0)
            {
                // 1. Generate the static dispatcher class (contains the core logic)
                string staticDispatcherCode = GenerateStaticDispatcherCode(handlerInfos, namespaces);
                context.AddSource("KyrolusSous.Mediator.GeneratedDispatcher.g.cs", SourceText.From(staticDispatcherCode, Encoding.UTF8));

                // 2. Generate the class implementing IMediatorDispatcher
                string dispatcherImplCode = GenerateDispatcherImplementation();
                context.AddSource("KyrolusSous.Mediator.GeneratedDispatcherImpl.g.cs", SourceText.From(dispatcherImplCode, Encoding.UTF8));

                // 3. Generate the DI extension method to register the implementation
                string diExtensionCode = GenerateDIRegistration(availability.Runtime);
                context.AddSource("KyrolusSous.Mediator.GeneratedDIExtensions.g.cs", SourceText.From(diExtensionCode, Encoding.UTF8));

                // 4. Generate the DI extension method for Handler Registration ****
                string handlersDiExtensionCode = GenerateHandlerRegistrationMethod(handlerInfos, openGenericHandlers, namespaces, availability.Runtime);
                context.AddSource("KyrolusSous.Mediator.GeneratedHandlersDIExtensions.g.cs", SourceText.From(handlersDiExtensionCode, Encoding.UTF8));

                // 5. Generate the closed pipeline wrappers, which is what makes the send path
                //    publishable with NativeAOT. Skipped when the runtime package is absent: the
                //    factory and the interface it implements both live there, so the file would
                //    simply fail to compile.
                if (availability.Runtime)
                {
                    string wrapperSourceCode = GeneratePipelineWrapperSource(handlerInfos);
                    context.AddSource("KyrolusSous.Mediator.GeneratedPipelineWrappers.g.cs", SourceText.From(wrapperSourceCode, Encoding.UTF8));

                    // 6. Exception actions and handlers, bound the same way. Emitted even when both
                    //    lists are empty, because a miss is not an error here: the behavior falls
                    //    back to reflection where that is possible, which keeps actions declared in
                    //    a referenced assembly working exactly as they do today.
                    string exceptionSourceCode = GenerateExceptionDispatchSource(exceptionActions, exceptionHandlers);
                    context.AddSource("KyrolusSous.Mediator.GeneratedExceptionDispatch.g.cs", SourceText.From(exceptionSourceCode, Encoding.UTF8));
                }
            }
        }

        // --- Helper Record ---
        /// <summary>Helper class to store extracted information about a specific handler.</summary>
        private sealed class HandlerInfo(INamedTypeSymbol handlerType, INamedTypeSymbol requestType, ITypeSymbol responseType, string interfaceFullName, bool isStream)
        {
            public INamedTypeSymbol HandlerType { get; } = handlerType;
            public INamedTypeSymbol RequestType { get; } = requestType;
            public ITypeSymbol ResponseType { get; } = responseType;
            public string InterfaceFullName { get; } = interfaceFullName;
            public bool IsStream { get; } = isStream;
        }

        private sealed class OpenGenericHandlerInfo(INamedTypeSymbol handlerType, INamedTypeSymbol interfaceType)
        {
            public INamedTypeSymbol HandlerType { get; } = handlerType;
            public INamedTypeSymbol InterfaceType { get; } = interfaceType;
        }

        private sealed class HandlerInterfaceDefinitions(
            INamedTypeSymbol unitSymbol,
            INamedTypeSymbol queryHandlerDef,
            INamedTypeSymbol commandHandlerDef,
            INamedTypeSymbol commandHandlerWithResponseDef,
            INamedTypeSymbol requestHandlerDef,
            INamedTypeSymbol requestHandlerWithoutResponseDef,
            INamedTypeSymbol streamRequestHandlerDef,
            INamedTypeSymbol? exceptionActionDef,
            INamedTypeSymbol? exceptionHandlerDef)
        {
            /// <summary>Null only if the abstractions predate exception actions; collection is then skipped.</summary>
            public INamedTypeSymbol? ExceptionActionDef { get; } = exceptionActionDef;

            public INamedTypeSymbol? ExceptionHandlerDef { get; } = exceptionHandlerDef;

            public INamedTypeSymbol UnitSymbol { get; } = unitSymbol;
            public INamedTypeSymbol QueryHandlerDef { get; } = queryHandlerDef;
            public INamedTypeSymbol CommandHandlerDef { get; } = commandHandlerDef;
            public INamedTypeSymbol CommandHandlerWithResponseDef { get; } = commandHandlerWithResponseDef;
            public INamedTypeSymbol RequestHandlerDef { get; } = requestHandlerDef;
            public INamedTypeSymbol RequestHandlerWithoutResponseDef { get; } = requestHandlerWithoutResponseDef;
            public INamedTypeSymbol StreamRequestHandlerDef { get; } = streamRequestHandlerDef;

            /// <summary>
            /// Resolves the interfaces from a compilation, or <see langword="null"/> if any is
            /// missing - which means the abstractions package is not referenced.
            /// </summary>
            /// <remarks>
            /// Cheap to call per syntax node: <c>GetTypeByMetadataName</c> is served from the
            /// compilation's own cache.
            /// </remarks>
            public static HandlerInterfaceDefinitions? TryResolve(Compilation compilation)
            {
                var unit = compilation.GetTypeByMetadataName(UnitTypeFullName);
                var query = compilation.GetTypeByMetadataName(QueryHandlerInterfaceFullName);
                var command = compilation.GetTypeByMetadataName(CommandHandlerInterfaceFullName);
                var commandWithResponse = compilation.GetTypeByMetadataName(CommandHandlerWithResponseInterfaceFullName);
                var request = compilation.GetTypeByMetadataName(RequestHandlerInterfaceFullName);
                var requestWithoutResponse = compilation.GetTypeByMetadataName(RequestHandlerWithoutResponseInterfaceFullName);
                var stream = compilation.GetTypeByMetadataName(StreamRequestHandlerInterfaceFullName);
                var dispatcher = compilation.GetTypeByMetadataName(DispatcherInterfaceFullName);

                if (unit is null || query is null || command is null || commandWithResponse is null ||
                    request is null || requestWithoutResponse is null || stream is null || dispatcher is null)
                {
                    return null;
                }

                return new HandlerInterfaceDefinitions(
                    unit, query, command, commandWithResponse, request, requestWithoutResponse, stream,
                    compilation.GetTypeByMetadataName(ExceptionActionInterfaceFullName),
                    compilation.GetTypeByMetadataName(ExceptionHandlerInterfaceFullName));
            }
        }

        // --- Equatable models carried through the incremental pipeline ---
        // Everything below is plain data. Roslyn compares a pipeline stage's output to decide
        // whether downstream work can be skipped, and it compares with EqualityComparer<T>.Default,
        // so anything flowing through must be equal by value. Records of strings and bools are;
        // Roslyn symbols are not.

        /// <summary>One dispatch entry: which handler serves which request, and what it returns.</summary>
        private sealed record HandlerModel(
            string HandlerFullName,
            string RequestFullName,
            string ResponseFullName,
            string InterfaceFullName,
            bool IsStream);

        /// <summary>An open generic handler, registered by its unbound type.</summary>
        private sealed record OpenGenericModel(string HandlerOpenName, string InterfaceOpenName);

        /// <summary>
        /// One (request, exception) pair an exception action was declared for.
        /// </summary>
        /// <remarks>
        /// The implementing class is deliberately absent. The table only needs to know the
        /// combination exists; which implementations answer to it is the container's business, and
        /// asking it at runtime keeps registrations made by hand working too.
        /// </remarks>
        private sealed record ExceptionActionModel(string RequestFullName, string ExceptionFullName);

        /// <summary>One (request, exception, response) triple an exception handler was declared for.</summary>
        private sealed record ExceptionHandlerModel(
            string RequestFullName,
            string ExceptionFullName,
            string ResponseFullName);

        /// <summary>Everything one candidate class contributes.</summary>
        /// <param name="Handlers">Dispatch entries, one per handler interface the class implements.</param>
        /// <param name="OpenGenerics">Open generic registrations; empty for a closed class.</param>
        /// <param name="Namespaces">
        /// Semicolon-joined rather than a collection, so the record stays comparable by value.
        /// </param>
        /// <param name="ExceptionActions">Exception action declarations; usually empty.</param>
        /// <param name="ExceptionHandlers">Exception handler declarations; usually empty.</param>
        private sealed record ClassHandlerModel(
            EquatableArray<HandlerModel> Handlers,
            EquatableArray<OpenGenericModel> OpenGenerics,
            string Namespaces,
            EquatableArray<ExceptionActionModel> ExceptionActions,
            EquatableArray<ExceptionHandlerModel> ExceptionHandlers);

        /// <summary>
        /// <see cref="ImmutableArray{T}"/> compares by reference, which would make every pipeline
        /// output look changed. This compares element by element instead.
        /// </summary>
        private readonly struct EquatableArray<T>(ImmutableArray<T> items) : IEquatable<EquatableArray<T>>
            where T : IEquatable<T>
        {
            private readonly ImmutableArray<T> _items = items;


            /// <summary>The items, treating the uninitialised struct as empty.</summary>
            public ImmutableArray<T> Items => _items.IsDefault ? ImmutableArray<T>.Empty : _items;

            public bool Equals(EquatableArray<T> other) => Items.SequenceEqual(other.Items);

            public override bool Equals(object? obj) => obj is EquatableArray<T> other && Equals(other);

            public override int GetHashCode()
            {
                unchecked
                {
                    var hash = 17;
                    foreach (var item in Items)
                    {
                        hash = (hash * 31) + (item?.GetHashCode() ?? 0);
                    }

                    return hash;
                }
            }
        }

        // --- Helper Methods ---

        /// <summary>
        /// Analyzes a class symbol to determine if it implements one of the KyrolusMediator handler interfaces
        /// and extracts the request and response types.
        /// </summary>
        /// <summary>
        /// Yields one <see cref="HandlerInfo"/> per handler interface the class implements.
        /// </summary>
        /// <remarks>
        /// Every match is returned, not just the first. A single class may legitimately handle
        /// several messages - <c>class Foo : IKyrolusRequestHandler&lt;A, string&gt;,
        /// IKyrolusRequestHandler&lt;B, string&gt;</c> - and returning after the first match left
        /// the rest with no generated dispatch entry at all, so sending them fell through to the
        /// reflection fallback or failed outright.
        /// </remarks>
        private static IEnumerable<HandlerInfo> GetHandlerInfos(INamedTypeSymbol handlerSymbol, HandlerInterfaceDefinitions defs)
        {
            // One dispatch entry per (request, response, isStream). AllInterfaces reports inherited
            // interfaces too, and the handler interfaces form a hierarchy - IKyrolusQueryHandler<T,R>
            // derives from IKyrolusRequestHandler<T,R> - so a single query handler matches twice for
            // the same message. Both matches would emit the same dictionary key and the same call,
            // making the second assignment dead code.
            var emitted = new HashSet<(ISymbol Request, ISymbol Response, bool IsStream)>(
                RequestResponseComparer.Instance);

            // Iterate through all interfaces (including inherited ones)
            foreach (var iface in handlerSymbol.AllInterfaces)
            {
                // Ensure it's a constructed generic type (e.g., IKyrolusCommandHandler<MyCommand, Unit>)
                if (!iface.IsGenericType || iface.ConstructedFrom == null) continue;

                if (!TryMatchHandlerInterface(iface, defs, out var reqType, out var resType, out var isStream))
                {
                    continue;
                }
                string ifaceName = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat); // Get full name like IKyrolusCommandHandler<NS.Req, NS.Resp>

                // If a match was found and types were extracted successfully
                if (reqType != null && resType != null && emitted.Add((reqType, resType, isStream)))
                {
                    yield return new HandlerInfo(handlerSymbol, reqType, resType, ifaceName, isStream);
                }
            }
        }

        /// <summary>
        /// Compares (request, response, isStream) triples, using Roslyn's symbol comparison for the
        /// two type symbols - reference equality is not reliable for them.
        /// </summary>
        private sealed class RequestResponseComparer : IEqualityComparer<(ISymbol Request, ISymbol Response, bool IsStream)>
        {
            public static readonly RequestResponseComparer Instance = new();

            public bool Equals(
                (ISymbol Request, ISymbol Response, bool IsStream) x,
                (ISymbol Request, ISymbol Response, bool IsStream) y)
                => x.IsStream == y.IsStream
                   && SymbolEqualityComparer.Default.Equals(x.Request, y.Request)
                   && SymbolEqualityComparer.Default.Equals(x.Response, y.Response);

            public int GetHashCode((ISymbol Request, ISymbol Response, bool IsStream) obj)
            {
                unchecked
                {
                    var hash = SymbolEqualityComparer.Default.GetHashCode(obj.Request);
                    hash = (hash * 397) ^ SymbolEqualityComparer.Default.GetHashCode(obj.Response);
                    return (hash * 397) ^ obj.IsStream.GetHashCode();
                }
            }
        }

        private static bool TryMatchHandlerInterface(
            INamedTypeSymbol iface,
            HandlerInterfaceDefinitions defs,
            out INamedTypeSymbol? reqType,
            out ITypeSymbol? resType,
            out bool isStream)
        {
            reqType = null;
            resType = null;
            isStream = false;

            var originalDef = iface.OriginalDefinition; // Get the unbound generic definition (e.g., IKyrolusCommandHandler<,>)
            if (iface.TypeArguments.Length == 2)
            {
                if (SymbolEqualityComparer.Default.Equals(originalDef, defs.QueryHandlerDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.CommandHandlerWithResponseDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.RequestHandlerDef))
                {
                    reqType = iface.TypeArguments[0] as INamedTypeSymbol;
                    resType = iface.TypeArguments[1];
                    return true;
                }
                if (SymbolEqualityComparer.Default.Equals(originalDef, defs.StreamRequestHandlerDef))
                {
                    reqType = iface.TypeArguments[0] as INamedTypeSymbol;
                    resType = iface.TypeArguments[1];
                    isStream = true;
                    return true;
                }
                return false;
            }

            if (iface.TypeArguments.Length == 1 &&
                (SymbolEqualityComparer.Default.Equals(originalDef, defs.CommandHandlerDef) ||
                 SymbolEqualityComparer.Default.Equals(originalDef, defs.RequestHandlerWithoutResponseDef)))
            {
                reqType = iface.TypeArguments[0] as INamedTypeSymbol;
                resType = defs.UnitSymbol;
                return true;
            }

            return false;
        }

        /// <summary>
        /// Records the (request, exception) and (request, exception, response) combinations this
        /// class participates in.
        /// </summary>
        /// <remarks>
        /// A class may implement several of each - one action per exception type is common - so
        /// every match is recorded rather than the first.
        /// </remarks>
        private static void CollectExceptionParticipants(
            INamedTypeSymbol classSymbol,
            HandlerInterfaceDefinitions defs,
            ImmutableArray<ExceptionActionModel>.Builder actions,
            ImmutableArray<ExceptionHandlerModel>.Builder handlers)
        {
            foreach (var iface in classSymbol.AllInterfaces)
            {
                if (!iface.IsGenericType) continue;

                var originalDef = iface.OriginalDefinition;

                if (defs.ExceptionActionDef is not null
                    && iface.TypeArguments.Length == 2
                    && SymbolEqualityComparer.Default.Equals(originalDef, defs.ExceptionActionDef))
                {
                    actions.Add(new ExceptionActionModel(
                        iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        iface.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
                    continue;
                }

                if (defs.ExceptionHandlerDef is not null
                    && iface.TypeArguments.Length == 3
                    && SymbolEqualityComparer.Default.Equals(originalDef, defs.ExceptionHandlerDef))
                {
                    handlers.Add(new ExceptionHandlerModel(
                        iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        iface.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        iface.TypeArguments[2].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
                }
            }
        }

        private static IEnumerable<OpenGenericHandlerInfo> TryGetOpenGenericHandlerRegistrations(
            INamedTypeSymbol handlerSymbol,
            HandlerInterfaceDefinitions defs)
        {
            foreach (var iface in handlerSymbol.AllInterfaces)
            {
                if (!iface.IsGenericType || iface.ConstructedFrom is null) continue;

                var originalDef = iface.OriginalDefinition;
                if (SymbolEqualityComparer.Default.Equals(originalDef, defs.QueryHandlerDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.CommandHandlerDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.CommandHandlerWithResponseDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.RequestHandlerDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.RequestHandlerWithoutResponseDef) ||
                    SymbolEqualityComparer.Default.Equals(originalDef, defs.StreamRequestHandlerDef))
                {
                    yield return new OpenGenericHandlerInfo(handlerSymbol.OriginalDefinition, originalDef);
                }
            }
        }

        /// <summary>
        /// Generates the source code for the static GeneratedMediatorDispatcher class.
        /// </summary>
        private static string GenerateStaticDispatcherCode(List<HandlerModel> handlerInfos, HashSet<string> namespaces)
        {
            var sb = new StringBuilder();
            // --- File Header ---
            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine(NullableEnable);
            sb.AppendLine();

            // --- Using Statements ---
            foreach (var ns in namespaces.OrderBy(n => n)) sb.AppendLine($"using {ns};");
            sb.AppendLine();

            // --- Namespace and Class Definition ---
            sb.AppendLine("namespace KyrolusSous.Mediator.Generated");
            sb.AppendLine(OpenBrace);
            sb.AppendLine(CompilerGeneratedAttribute);
            sb.AppendLine("    internal static class GeneratedMediatorDispatcher");
            sb.AppendLine(Indent4OpenBrace);

            // --- Dictionaries ---
            var streamHandlerCount = handlerInfos.Count(info => info.IsStream);
            sb.AppendLine("        // Commands carry no response type, so the request type alone identifies them.");
            sb.AppendLine($"        private static readonly Dictionary<Type, Func<object, IServiceProvider, CancellationToken, Task>> s_commandDispatchers = new({handlerInfos.Count});");
            sb.AppendLine("        // Keyed on (request type, response type). The request type alone is not enough:");
            sb.AppendLine("        // one request may declare IKyrolusRequest<> for more than one response, and a");
            sb.AppendLine("        // single key would silently keep whichever entry was written last.");
            sb.AppendLine($"        private static readonly Dictionary<(Type RequestType, Type ResponseType), Func<object, IServiceProvider, CancellationToken, Task<object>>> s_requestDispatchers = new({handlerInfos.Count});");
            sb.AppendLine($"        private static readonly Dictionary<(Type RequestType, Type ResponseType), Func<object, IServiceProvider, CancellationToken, IAsyncEnumerable<object>>> s_streamDispatchers = new({streamHandlerCount});");
            sb.AppendLine();

            // --- Static Constructor ---
            sb.AppendLine("        static GeneratedMediatorDispatcher()");
            sb.AppendLine(Indent8OpenBrace);

            // --- Populate Dictionaries ---
            foreach (var info in handlerInfos)
            {
                string hFullName = info.HandlerFullName;
                string rFullName = info.RequestFullName;
                string respFullName = info.ResponseFullName;
                string iFullName = info.InterfaceFullName;
                bool isCmd = respFullName == UnitQualifiedName;

                sb.AppendLine($"            // Handler: {hFullName} Request: {rFullName}");
                if (info.IsStream)
                {
                    sb.AppendLine($"            s_streamDispatchers[(typeof({rFullName}), typeof({respFullName}))] = (req, sp, ct) =>");
                    sb.AppendLine($"            {{ var handler = ({iFullName})sp.GetRequiredService<{hFullName}>(); return CastStreamToObject(handler.Handle(({rFullName})req, ct), ct); }};");
                }
                else if (isCmd)
                {
                    sb.AppendLine($"            s_commandDispatchers[typeof({rFullName})] = async (req, sp, ct) =>");
                    sb.AppendLine($"            {{ var handler = ({iFullName})sp.GetRequiredService<{hFullName}>(); await handler.Handle(({rFullName})req, ct); }};");
                }
                else
                {
                    sb.AppendLine($"            s_requestDispatchers[(typeof({rFullName}), typeof({respFullName}))] = async (req, sp, ct) =>");
                    sb.AppendLine($"            {{ var handler = ({iFullName})sp.GetRequiredService<{hFullName}>(); var result = await handler.Handle(({rFullName})req, ct); return (object)result!; }};");
                }
                sb.AppendLine();
            }
            sb.AppendLine(Indent8CloseBrace); // End static constructor
            sb.AppendLine();

            // --- Dispatch Methods ---
            GenerateDispatchMethod(sb, isCommand: true);
            GenerateDispatchMethod(sb, isCommand: false);
            GenerateStreamDispatchMethod(sb);

            sb.AppendLine(Indent4CloseBrace); // End class
            sb.AppendLine(CloseBrace); // End namespace
            return sb.ToString();
        }

        /// <summary>
        /// Generates the class implementing IMediatorDispatcher.
        /// </summary>
        private static string GenerateDispatcherImplementation()
        {
            var sb = new StringBuilder();
            string interfaceFullName = DispatcherInterfaceQualifiedName;
            string interfaceNamespace = DispatcherInterfaceNamespace;

            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine(NullableEnable);
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine($"using {interfaceNamespace}; // Namespace of IMediatorDispatcher");
            sb.AppendLine();
            sb.AppendLine("namespace KyrolusSous.Mediator.Generated"); // Keep in Generated namespace
            sb.AppendLine(OpenBrace);
            sb.AppendLine("    /// <summary>Implements the internal dispatcher interface by delegating to the static dispatcher.</summary>");
            sb.AppendLine(CompilerGeneratedAttribute);
            sb.AppendLine($"    internal sealed class GeneratedDispatcher : {interfaceFullName}");
            sb.AppendLine(Indent4OpenBrace);
            sb.AppendLine("        public Task<TResponse> DispatchRequestAsync<TResponse>(object request, IServiceProvider sp, CancellationToken ct)");
            sb.AppendLine("            => GeneratedMediatorDispatcher.DispatchRequestAsync<TResponse>(request, sp, ct);");
            sb.AppendLine();
            sb.AppendLine("        public Task DispatchCommandAsync(object command, IServiceProvider sp, CancellationToken ct)");
            sb.AppendLine("            => GeneratedMediatorDispatcher.DispatchCommandAsync(command, sp, ct);");
            sb.AppendLine();
            sb.AppendLine("        public IAsyncEnumerable<TResponse> DispatchStreamAsync<TResponse>(object request, IServiceProvider sp, CancellationToken ct)");
            sb.AppendLine("            => GeneratedMediatorDispatcher.DispatchStreamAsync<TResponse>(request, sp, ct);");
            sb.AppendLine(Indent4CloseBrace);
            sb.AppendLine(CloseBrace);
            return sb.ToString();
        }

        /// <summary>
        /// Generates the DI extension method for registering the IMediatorDispatcher implementation.
        /// </summary>
        private static string GenerateDIRegistration(bool runtimeAvailable)
        {
            var sb = new StringBuilder();
            string interfaceFullName = DispatcherInterfaceQualifiedName;
            string implementationFullName = "KyrolusSous.Mediator.Generated.GeneratedDispatcher"; // Full name of the implementation class
            string interfaceNamespace = DispatcherInterfaceNamespace;

            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine(NullableEnable);
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
            sb.AppendLine($"using {interfaceNamespace}; // Namespace of IMediatorDispatcher");
            sb.AppendLine($"using KyrolusSous.Mediator.Generated; // Namespace of GeneratedDispatcher implementation");
            sb.AppendLine();
            // Put extensions in a relevant namespace, e.g., Microsoft.Extensions.DependencyInjection for discoverability
            sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
            sb.AppendLine(OpenBrace);
            sb.AppendLine("    /// <summary>Extension methods for registering generated KyrolusSous.Mediator components.</summary>");
            sb.AppendLine(CompilerGeneratedAttribute);
            sb.AppendLine("    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]"); // Hide from intellisense? Optional
            sb.AppendLine("    public static class KyrolusMediatorGeneratedDIExtensions");
            sb.AppendLine(Indent4OpenBrace);
            sb.AppendLine("        /// <summary>Registers the generated dispatcher implementation.</summary>");
            sb.AppendLine("        /// <remarks>Call this after registering handlers and before resolving IKyrolusMediatorSender.</remarks>");
            sb.AppendLine("        public static IServiceCollection AddKyrolusMediatorGeneratedDispatcher(this IServiceCollection services)");
            sb.AppendLine(Indent8OpenBrace);
            // Replace any existing dispatcher (e.g., reflection-based) with the generated one
            sb.AppendLine($"            services.Replace(ServiceDescriptor.Singleton<{interfaceFullName}, {implementationFullName}>());");
            if (runtimeAvailable)
            {
                sb.AppendLine();
                sb.AppendLine("            // Lets the sender take every pipeline wrapper from the table below instead of");
                sb.AppendLine("            // closing the wrapper types with MakeGenericType, which NativeAOT cannot do.");
                sb.AppendLine($"            services.TryAddSingleton<{PipelineWrapperSourceInterfaceQualifiedName}, global::{PipelineWrapperSourceImplName}>();");
                sb.AppendLine();
                sb.AppendLine("            // Same idea for the exception behavior: bound calls instead of a handler interface");
                sb.AppendLine("            // closed over the response type, which is the part NativeAOT cannot do.");
                sb.AppendLine($"            services.TryAddSingleton<{ExceptionDispatchSourceInterfaceQualifiedName}, global::{ExceptionDispatchSourceImplName}>();");
            }
            sb.AppendLine("            return services;");
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine(Indent4CloseBrace);
            sb.AppendLine(CloseBrace);
            return sb.ToString();
        }
        /// <summary>
        /// Generates the table of pipeline wrappers, one entry per (request, response) pair.
        /// </summary>
        /// <remarks>
        /// This is the file that makes the send path publishable with NativeAOT. Each entry closes
        /// the wrapper through a static generic call with concrete type arguments, so the compiler
        /// sees the instantiation and emits it ahead of time. What it replaces - closing the type
        /// with <c>MakeGenericType</c> - works only where the runtime can produce code on demand,
        /// and for a value-type response it cannot.
        /// </remarks>
        private static string GeneratePipelineWrapperSource(List<HandlerModel> handlerInfos)
        {
            var sb = new StringBuilder();
            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine(NullableEnable);
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace KyrolusSous.Mediator.Generated");
            sb.AppendLine(OpenBrace);
            sb.AppendLine("    /// <summary>Pipeline wrappers closed at compile time, so none has to be built at runtime.</summary>");
            sb.AppendLine(CompilerGeneratedAttribute);
            sb.AppendLine($"    internal sealed class GeneratedPipelineWrapperSource : {PipelineWrapperSourceInterfaceQualifiedName}");
            sb.AppendLine(Indent4OpenBrace);

            AppendWrapperTable(sb, "s_requestWrappers", "CreateRequest", DistinctPairs(handlerInfos, isStream: false));
            AppendWrapperTable(sb, "s_streamWrappers", "CreateStream", DistinctPairs(handlerInfos, isStream: true));
            AppendResponseTypeTable(sb, "s_requestResponses", DistinctPairs(handlerInfos, isStream: false));
            AppendResponseTypeTable(sb, "s_streamResponses", DistinctPairs(handlerInfos, isStream: true));

            // Null rather than an exception for a miss: an open generic handler is closed only where
            // it is used, so the generator never sees the pair. The sender decides what to do about
            // that, and only it knows whether a runtime fallback is available.
            sb.AppendLine("        public object? CreateRequestWrapper(Type requestType, Type responseType)");
            sb.AppendLine("            => s_requestWrappers.TryGetValue((requestType, responseType), out var factory) ? factory() : null;");
            sb.AppendLine();
            sb.AppendLine("        public object? CreateStreamWrapper(Type requestType, Type responseType)");
            sb.AppendLine("            => s_streamWrappers.TryGetValue((requestType, responseType), out var factory) ? factory() : null;");
            sb.AppendLine();
            sb.AppendLine("        public Type? GetResponseType(Type requestType, bool stream)");
            sb.AppendLine("            => (stream ? s_streamResponses : s_requestResponses).TryGetValue(requestType, out var responseType) ? responseType : null;");

            sb.AppendLine(Indent4CloseBrace);
            sb.AppendLine(CloseBrace);
            return sb.ToString();
        }

        /// <summary>
        /// Generates the exception action and handler tables.
        /// </summary>
        /// <remarks>
        /// The two <c>Bind</c> helpers are written once and instantiated per combination by the
        /// tables, so each instantiation is a concrete static call the compiler emits ahead of time.
        /// The handler table is the one that matters for NativeAOT: its third type argument is the
        /// response, and a response of <c>int</c> is exactly what <c>MakeGenericType</c> cannot
        /// produce in an application published ahead of time.
        /// </remarks>
        private static string GenerateExceptionDispatchSource(
            List<ExceptionActionModel> actions,
            List<ExceptionHandlerModel> handlers)
        {
            var distinctActions = actions
                .Distinct()
                .OrderBy(a => a.RequestFullName, StringComparer.Ordinal)
                .ThenBy(a => a.ExceptionFullName, StringComparer.Ordinal)
                .ToList();

            var distinctHandlers = handlers
                .Distinct()
                .OrderBy(h => h.RequestFullName, StringComparer.Ordinal)
                .ThenBy(h => h.ExceptionFullName, StringComparer.Ordinal)
                .ThenBy(h => h.ResponseFullName, StringComparer.Ordinal)
                .ToList();

            const string ActionListType = "IReadOnlyList<(Type ActionType, Func<CancellationToken, Task> Invoke)>";
            const string HandlerListType = "IReadOnlyList<Func<CancellationToken, Task>>";

            var sb = new StringBuilder();
            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine(NullableEnable);
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();
            sb.AppendLine("namespace KyrolusSous.Mediator.Generated");
            sb.AppendLine(OpenBrace);
            sb.AppendLine("    /// <summary>Exception actions and handlers bound at compile time.</summary>");
            sb.AppendLine(CompilerGeneratedAttribute);
            sb.AppendLine($"    internal sealed class GeneratedRequestExceptionDispatchSource : {ExceptionDispatchSourceInterfaceQualifiedName}");
            sb.AppendLine(Indent4OpenBrace);

            sb.AppendLine($"        private static readonly Dictionary<(Type RequestType, Type ExceptionType), Func<object, Exception, IServiceProvider, {ActionListType}>> s_actions = new({distinctActions.Count})");
            sb.AppendLine(Indent8OpenBrace);
            foreach (var action in distinctActions)
            {
                sb.AppendLine($"            [(typeof({action.RequestFullName}), typeof({action.ExceptionFullName}))] = static (request, exception, serviceProvider) => BindActions<{action.RequestFullName}, {action.ExceptionFullName}>(request, exception, serviceProvider),");
            }
            sb.AppendLine("        };");
            sb.AppendLine();

            sb.AppendLine($"        private static readonly Dictionary<(Type RequestType, Type ExceptionType, Type ResponseType), Func<object, Exception, object, IServiceProvider, {HandlerListType}>> s_handlers = new({distinctHandlers.Count})");
            sb.AppendLine(Indent8OpenBrace);
            foreach (var handler in distinctHandlers)
            {
                sb.AppendLine($"            [(typeof({handler.RequestFullName}), typeof({handler.ExceptionFullName}), typeof({handler.ResponseFullName}))] = static (request, exception, state, serviceProvider) => BindHandlers<{handler.RequestFullName}, {handler.ExceptionFullName}, {handler.ResponseFullName}>(request, exception, state, serviceProvider),");
            }
            sb.AppendLine("        };");
            sb.AppendLine();

            sb.AppendLine($"        private static {ActionListType} BindActions<TRequest, TException>(object request, Exception exception, IServiceProvider serviceProvider)");
            sb.AppendLine("            where TException : Exception");
            sb.AppendLine(Indent8OpenBrace);
            sb.AppendLine("            var typedRequest = (TRequest)request;");
            sb.AppendLine("            var typedException = (TException)exception;");
            sb.AppendLine("            var invocations = new List<(Type, Func<CancellationToken, Task>)>();");
            sb.AppendLine($"            foreach (var action in serviceProvider.GetServices<{ExceptionActionQualifiedName}<TRequest, TException>>())");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                invocations.Add((action.GetType(), cancellationToken => action.Execute(typedRequest, typedException, cancellationToken)));");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
            sb.AppendLine("            return invocations;");
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine();

            sb.AppendLine($"        private static {HandlerListType} BindHandlers<TRequest, TException, TResponse>(object request, Exception exception, object state, IServiceProvider serviceProvider)");
            sb.AppendLine("            where TException : Exception");
            sb.AppendLine(Indent8OpenBrace);
            sb.AppendLine("            var typedRequest = (TRequest)request;");
            sb.AppendLine("            var typedException = (TException)exception;");
            sb.AppendLine($"            var typedState = ({ExceptionHandlerStateQualifiedName}<TResponse>)state;");
            sb.AppendLine("            var invocations = new List<Func<CancellationToken, Task>>();");
            sb.AppendLine($"            foreach (var handler in serviceProvider.GetServices<{ExceptionHandlerQualifiedName}<TRequest, TException, TResponse>>())");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                invocations.Add(cancellationToken => handler.Handle(typedRequest, typedException, typedState, cancellationToken));");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
            sb.AppendLine("            return invocations;");
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine();

            sb.AppendLine($"        public {ActionListType}? CreateActionInvocations(Type requestType, Type exceptionType, object request, Exception exception, IServiceProvider serviceProvider)");
            sb.AppendLine("            => s_actions.TryGetValue((requestType, exceptionType), out var bind) ? bind(request, exception, serviceProvider) : null;");
            sb.AppendLine();
            sb.AppendLine($"        public {HandlerListType}? CreateHandlerInvocations(Type requestType, Type exceptionType, Type responseType, object request, Exception exception, object state, IServiceProvider serviceProvider)");
            sb.AppendLine("            => s_handlers.TryGetValue((requestType, exceptionType, responseType), out var bind) ? bind(request, exception, state, serviceProvider) : null;");

            sb.AppendLine(Indent4CloseBrace);
            sb.AppendLine(CloseBrace);
            return sb.ToString();
        }

        /// <summary>The (request, response) pairs of one dispatch shape, without duplicates.</summary>
        /// <remarks>
        /// Distinct because a class handling one message through two interfaces contributes a
        /// <see cref="HandlerModel"/> for each, while the wrapper is keyed on the pair alone and a
        /// repeated key would not compile. Ordered so identical input produces an identical file.
        /// </remarks>
        private static List<(string Request, string Response)> DistinctPairs(List<HandlerModel> handlerInfos, bool isStream)
            => handlerInfos
                .Where(info => info.IsStream == isStream)
                .Select(info => (Request: info.RequestFullName, Response: info.ResponseFullName))
                .Distinct()
                .OrderBy(pair => pair.Request, StringComparer.Ordinal)
                .ThenBy(pair => pair.Response, StringComparer.Ordinal)
                .ToList();

        /// <summary>
        /// Emits the request-to-response lookup the untyped <c>SendAsync(object)</c> overloads need.
        /// </summary>
        /// <remarks>
        /// A request that declares more than one response is deliberately left out. Reading the
        /// answer off the type at runtime picks whichever interface comes back first, which is a
        /// coin toss; omitting it makes the sender say so instead, and the overloads that name the
        /// response still work.
        /// </remarks>
        private static void AppendResponseTypeTable(
            StringBuilder sb,
            string fieldName,
            List<(string Request, string Response)> pairs)
        {
            var unambiguous = pairs
                .GroupBy(pair => pair.Request, StringComparer.Ordinal)
                .Where(group => group.Count() == 1)
                .Select(group => group.First())
                .ToList();

            sb.AppendLine($"        private static readonly Dictionary<Type, Type> {fieldName} = new({unambiguous.Count})");
            sb.AppendLine(Indent8OpenBrace);
            foreach (var (request, response) in unambiguous)
            {
                sb.AppendLine($"            [typeof({request})] = typeof({response}),");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        private static void AppendWrapperTable(
            StringBuilder sb,
            string fieldName,
            string factoryMethod,
            List<(string Request, string Response)> pairs)
        {
            sb.AppendLine($"        private static readonly Dictionary<(Type RequestType, Type ResponseType), Func<object>> {fieldName} = new({pairs.Count})");
            sb.AppendLine(Indent8OpenBrace);
            foreach (var (request, response) in pairs)
            {
                sb.AppendLine($"            [(typeof({request}), typeof({response}))] = static () => {PipelineWrapperFactoryQualifiedName}.{factoryMethod}<{request}, {response}>(),");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        // **** NEW HELPER METHOD ****
        /// <summary>
        /// Generates the DI extension method for registering all discovered concrete handlers.
        /// </summary>
        private static string GenerateHandlerRegistrationMethod(
            List<HandlerModel> handlerInfos,
            List<OpenGenericModel> openGenericHandlers,
            HashSet<string> namespaces,
            bool runtimeAvailable)
        {
            var sb = new StringBuilder();
            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine(NullableEnable);
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
            // Add using statements for handler namespaces collected previously
            foreach (var ns in namespaces.Where(n => !n.StartsWith("System") && !n.StartsWith("Microsoft") && !n.StartsWith("KyrolusSous.Mediator")) // Avoid redundant usings
                                        .OrderBy(n => n))
            {
                sb.AppendLine($"using {ns};");
            }
            sb.AppendLine();
            // Place in a common namespace for extensions
            sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
            sb.AppendLine(OpenBrace);
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Extension methods for registering KyrolusSous.Mediator handlers discovered by the generator.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine(CompilerGeneratedAttribute);
            sb.AppendLine("    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine("    public static class KyrolusMediatorGeneratedHandlersDIExtensions");
            sb.AppendLine(Indent4OpenBrace);
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Registers all concrete Command and Query handlers discovered by the KyrolusSous.Mediator.Generator.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static IServiceCollection AddKyrolusMediatorHandlers(this IServiceCollection services)");
            sb.AppendLine(Indent8OpenBrace);

            // Distinct by handler type: a class implementing several handler interfaces has one
            // HandlerInfo per interface, but the concrete type only needs registering once.
            var distinctHandlerTypes = handlerInfos
                .Select(info => info.HandlerFullName)
                .Distinct()
                .OrderBy(name => name, StringComparer.Ordinal);

            foreach (var handlerFullName in distinctHandlerTypes)
            {
                // Register the concrete handler type. Transient lifetime is typical for handlers.
                sb.AppendLine($"            services.TryAddTransient<{handlerFullName}>();");

                // --- Optional: Registering against specific interfaces ---
                // You might also want to register the handler against its specific closed-generic interface
                // although resolving the concrete type directly is often sufficient if dependencies ask for the concrete type.
                // If you need to resolve handlers via their specific interface (e.g., IEnumerable<IKyrolusQueryHandler<...>>), uncomment below.
                // string interfaceFullName = info.InterfaceFullName; 
                // sb.AppendLine($"            services.TryAddTransient<{interfaceFullName}, {handlerFullName}>();");
                // --- End Optional ---
            }

            sb.AppendLine();
            // Register open generic handlers
            foreach (var info in openGenericHandlers)
            {
                sb.AppendLine($"            services.TryAddTransient(typeof({info.InterfaceOpenName}), typeof({info.HandlerOpenName}));");
            }
            sb.AppendLine();
            if (runtimeAvailable)
            {
                AppendClosedBuiltInBehaviors(sb, handlerInfos);
            }
            sb.AppendLine("            return services;");
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine(Indent4CloseBrace);
            sb.AppendLine(CloseBrace);
            return sb.ToString();
        }

        /// <summary>
        /// Emits the four built-in behaviors closed over every (request, response) pair.
        /// </summary>
        /// <remarks>
        /// The runtime registers the same four as open generics and leaves the container to close
        /// them, which it does with <c>MakeGenericType</c> - and refuses when a type argument is a
        /// value type in an application published ahead of time. Naming the closed types here means
        /// the compiler emits them, so nothing has to be built on demand.
        /// <para>
        /// Guarded on the same condition the runtime uses, so exactly one of the two sets is ever
        /// registered. Registering both would not be caught by <c>TryAddEnumerable</c> - an open
        /// descriptor and a closed one are different registrations - and every behavior would run
        /// twice.
        /// </para>
        /// </remarks>
        private static void AppendClosedBuiltInBehaviors(StringBuilder sb, List<HandlerModel> handlerInfos)
        {
            var requestPairs = DistinctPairs(handlerInfos, isStream: false);
            var streamPairs = DistinctPairs(handlerInfos, isStream: true);

            if (requestPairs.Count == 0 && streamPairs.Count == 0) return;

            sb.AppendLine("            // The built-in behaviors, closed at compile time. See AddBuiltInBehaviors in the");
            sb.AppendLine("            // runtime: it registers the same four as open generics and declines on this exact");
            sb.AppendLine("            // condition, so only one of the two sets is ever present.");
            sb.AppendLine("            if (!global::System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeSupported)");
            sb.AppendLine(Indent12OpenBrace);

            foreach (var (request, response) in requestPairs)
            {
                foreach (var behavior in BuiltInRequestBehaviors)
                {
                    sb.AppendLine(
                        $"                services.TryAddEnumerable(ServiceDescriptor.Transient<{PipelineBehaviorInterface}<{request}, {response}>, {behavior}<{request}, {response}>>());");
                }
            }

            foreach (var (request, response) in streamPairs)
            {
                sb.AppendLine(
                    $"                services.TryAddEnumerable(ServiceDescriptor.Transient<{StreamPipelineBehaviorInterface}<{request}, {response}>, {BuiltInStreamBehavior}<{request}, {response}>>());");
            }

            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
        }

        private static string GetOpenGenericTypeOf(INamedTypeSymbol symbol)
        {
            string ns = symbol.ContainingNamespace.ToDisplayString();
            string name = symbol.Name;
            int arity = symbol.Arity;
            string typeParams = arity == 0 ? string.Empty : $"<{new string(',', arity - 1)}>";
            return $"global::{ns}.{name}{typeParams}";
        }
        /// <summary>
        /// Helper method to generate the body of the static dispatch methods.
        /// </summary>
        private static void GenerateDispatchMethod(StringBuilder sb, bool isCommand)
        {
            string dictionaryName = isCommand ? "s_commandDispatchers" : "s_requestDispatchers";
            string inputParamName = isCommand ? "command" : "request";
            string returnType = isCommand ? "Task" : "Task<TResponse>";
            string methodName = isCommand ? "DispatchCommandAsync" : "DispatchRequestAsync";
            string genericParam = isCommand ? "" : "<TResponse>";
            string exceptionInterfaceText = isCommand ? "IKyrolusCommandHandler<...>" : "IKyrolusQueryHandler<...> or IKyrolusCommandHandler<..., TResponse>";
            string taskResultVar = "result";
            string awaitPrefix = isCommand ? "" : "async ";
            string inputParameterType = "object";
            string unitFullName = UnitQualifiedName;
            string localRequestVarName = isCommand ? "commandType" : "requestType";

            sb.AppendLine($"        /// <summary>Dispatches a {(isCommand ? "command (Task return)" : "request (TResponse return)")}.</summary>");
            sb.AppendLine($"        public static {awaitPrefix}{returnType} {methodName}{genericParam}({inputParameterType} {inputParamName}, IServiceProvider serviceProvider, CancellationToken cancellationToken)");
            sb.AppendLine(Indent8OpenBrace);
            sb.AppendLine($"            var {localRequestVarName} = {inputParamName}.GetType();"); // Get runtime type
            sb.AppendLine();
            sb.AppendLine($"            // Try finding the handler in the primary dictionary");
            sb.AppendLine(isCommand
                ? $"            if ({dictionaryName}.TryGetValue({localRequestVarName}, out var handlerFunc))"
                : $"            if ({dictionaryName}.TryGetValue(({localRequestVarName}, typeof(TResponse)), out var handlerFunc))");
            sb.AppendLine(Indent12OpenBrace);
            if (isCommand)
            { sb.AppendLine($"                return handlerFunc({inputParamName}, serviceProvider, cancellationToken);"); }
            else
            {
                sb.AppendLine($"                var {taskResultVar} = await handlerFunc({inputParamName}, serviceProvider, cancellationToken);");
                sb.AppendLine($"                // Check for null return from handler when TResponse is a non-nullable value type");
                sb.AppendLine($"                if ({taskResultVar} == null && default(TResponse) != null)");
                sb.AppendLine(Indent16OpenBrace);
                sb.AppendLine($"                   throw new InvalidCastException($\"[KyrolusMediator] Handler for {{{localRequestVarName}.FullName}} returned null, but expected non-nullable {{typeof(TResponse).FullName}}.\");");
                sb.AppendLine(Indent16CloseBrace);
                sb.AppendLine($"                return (TResponse){taskResultVar}!;"); // Cast/unbox result
            }
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
            sb.AppendLine($"            // Fallback logic if not found in the primary dictionary");
            if (isCommand)
            {
                // If DispatchCommandAsync called for something that returns Unit but was registered as Request
                sb.AppendLine($"            if (s_requestDispatchers.TryGetValue(({localRequestVarName}, typeof({unitFullName})), out var reqFunc))");
                sb.AppendLine(Indent12OpenBrace);
                sb.AppendLine($"                 // Found in request dispatcher (likely returns Unit); execute and return Task.");
                sb.AppendLine($"                 return reqFunc({inputParamName}, serviceProvider, cancellationToken); // Return Task<object> as Task");
                sb.AppendLine(Indent12CloseBrace);
            }
            else
            {
                // If DispatchRequestAsync<Unit> called for something registered as Command
                sb.AppendLine($"            if (typeof(TResponse) == typeof({unitFullName}) && s_commandDispatchers.TryGetValue({localRequestVarName}, out var cmdFunc))");
                sb.AppendLine(Indent12OpenBrace);
                sb.AppendLine($"                // Found in command dispatcher and expecting Unit; execute and return Unit.");
                sb.AppendLine($"                await cmdFunc({inputParamName}, serviceProvider, cancellationToken);");
                sb.AppendLine($"                return (TResponse)(object){unitFullName}.Value; // Box Unit and cast to TResponse (Unit)");
                sb.AppendLine(Indent12CloseBrace);
            }
            sb.AppendLine();
            AppendOpenGenericDispatchFallback(sb, isCommand, inputParamName, localRequestVarName);
            sb.AppendLine();
            sb.AppendLine($"            // No handler found after primary lookup and fallback.");
            // Generate the exception message string carefully
            sb.Append($"            throw new InvalidOperationException($\"[KyrolusMediator] No handler registered for {{{localRequestVarName}.FullName}}");
            if (!isCommand) { sb.Append($" returning {{typeof(TResponse).FullName}}"); }
            sb.Append($". Ensure the handler class is concrete, public, implements {exceptionInterfaceText}, and is registered in the dependency injection container.\");");
            sb.AppendLine(); // Add the semicolon and newline

            sb.AppendLine(Indent8CloseBrace); // End method
            sb.AppendLine();
        }

        private static void GenerateStreamDispatchMethod(StringBuilder sb)
        {
            sb.AppendLine("        /// <summary>Dispatches a streaming request.</summary>");
            sb.AppendLine("        public static IAsyncEnumerable<TResponse> DispatchStreamAsync<TResponse>(object request, IServiceProvider serviceProvider, CancellationToken cancellationToken)");
            sb.AppendLine(Indent8OpenBrace);
            sb.AppendLine("            var requestType = request.GetType();");
            sb.AppendLine();
            sb.AppendLine("            if (s_streamDispatchers.TryGetValue((requestType, typeof(TResponse)), out var handlerFunc))");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                return CastStreamFromObject<TResponse>(handlerFunc(request, serviceProvider, cancellationToken), requestType, cancellationToken);");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
            sb.AppendLine("            // Try resolving open generic stream handlers registered in DI.");
            AppendDynamicCodeGuard(sb, "stream handler", "requestType");
            sb.AppendLine("            var openHandlerType = typeof(IKyrolusStreamRequestHandler<,>).MakeGenericType(requestType, typeof(TResponse));");
            sb.AppendLine("            var openHandler = serviceProvider.GetService(openHandlerType);");
            sb.AppendLine("            if (openHandler is not null)");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                var method = openHandlerType.GetMethod(\"Handle\", new[] { requestType, typeof(CancellationToken) });");
            sb.AppendLine("                if (method is null) throw new InvalidOperationException($\"[KyrolusMediator] Could not find Handle(...) on {openHandlerType.FullName}.\");");
            sb.AppendLine("                var stream = (IAsyncEnumerable<TResponse>)method.Invoke(openHandler, new object[] { request, cancellationToken })!;");
            sb.AppendLine("                return stream;");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
            sb.AppendLine("            throw new InvalidOperationException($\"[KyrolusMediator] No stream handler registered for {requestType.FullName}. Ensure the handler class is concrete, public, implements IKyrolusStreamRequestHandler<..., ...>, and is registered in the dependency injection container.\");");
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine();

            sb.AppendLine("        private static async IAsyncEnumerable<object> CastStreamToObject<T>(IAsyncEnumerable<T> source, [EnumeratorCancellation] CancellationToken cancellationToken)");
            sb.AppendLine(Indent8OpenBrace);
            sb.AppendLine("            await foreach (var item in source.WithCancellation(cancellationToken).ConfigureAwait(false))");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                yield return item!;");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine();

            sb.AppendLine("        private static async IAsyncEnumerable<TResponse> CastStreamFromObject<TResponse>(IAsyncEnumerable<object> source, Type requestType, [EnumeratorCancellation] CancellationToken cancellationToken)");
            sb.AppendLine(Indent8OpenBrace);
            sb.AppendLine("            await foreach (var item in source.WithCancellation(cancellationToken).ConfigureAwait(false))");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                if (item is null)");
            sb.AppendLine(Indent16OpenBrace);
            sb.AppendLine("                    if (default(TResponse) is not null)");
            sb.AppendLine(Indent16OpenBrace);
            sb.AppendLine("                        throw new InvalidCastException($\"[KyrolusMediator] Stream handler for {requestType.FullName} returned null, but expected non-nullable {typeof(TResponse).FullName}.\");");
            sb.AppendLine(Indent16CloseBrace);
            sb.AppendLine();
            sb.AppendLine("                    yield return (TResponse)(object)default!;");
            sb.AppendLine("                    continue;");
            sb.AppendLine(Indent16CloseBrace);
            sb.AppendLine();
            sb.AppendLine("                if (item is TResponse typed)");
            sb.AppendLine(Indent16OpenBrace);
            sb.AppendLine("                    yield return typed;");
            sb.AppendLine("                    continue;");
            sb.AppendLine(Indent16CloseBrace);
            sb.AppendLine();
            sb.AppendLine("                throw new InvalidCastException($\"[KyrolusMediator] Stream handler for {requestType.FullName} returned item of type {item.GetType().FullName}, expected {typeof(TResponse).FullName}.\");");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine(Indent8CloseBrace);
            sb.AppendLine();
        }

        /// <summary>
        /// Emits the bail-out that stands in front of every open generic lookup.
        /// </summary>
        /// <remarks>
        /// An open generic handler is closed only where it is used, so the generator never sees the
        /// closed type and cannot put it in the dispatch table. Resolving one therefore needs
        /// <c>MakeGenericType</c>, which an application published ahead of time cannot do.
        /// <para>
        /// Written as an early throw rather than an <c>if</c> around the block for two reasons: the
        /// trimming and AOT analyzers recognise it as a feature guard and stop warning about the
        /// code that follows, and the message names the request instead of letting the failure
        /// surface from inside <c>MakeGenericType</c>, which names nothing useful.
        /// </para>
        /// </remarks>
        private static void AppendDynamicCodeGuard(StringBuilder sb, string what, string requestTypeVarName)
        {
            sb.AppendLine("            if (!System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeSupported)");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine($"                throw new InvalidOperationException($\"[KyrolusMediator] No generated {what} for {{{requestTypeVarName}.FullName}}, and this application was published without runtime code generation, so an open generic handler cannot be resolved either. Give the message a concrete, non-generic handler the generator can see.\");");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
        }

        private static void AppendOpenGenericDispatchFallback(StringBuilder sb, bool isCommand, string inputParamName, string localRequestVarName)
        {
            sb.AppendLine("            // Try resolving open generic handlers registered in DI.");
            AppendDynamicCodeGuard(sb, "handler", localRequestVarName);
            if (isCommand)
            {
                sb.AppendLine($"            var commandHandlerType = typeof(IKyrolusCommandHandler<>).MakeGenericType({localRequestVarName});");
                sb.AppendLine("            var commandHandler = serviceProvider.GetService(commandHandlerType);");
                sb.AppendLine("            if (commandHandler is not null)");
                sb.AppendLine(Indent12OpenBrace);
                sb.AppendLine($"                var method = commandHandlerType.GetMethod(\"Handle\", new[] {{ {localRequestVarName}, typeof(CancellationToken) }});");
                sb.AppendLine("                if (method is null) throw new InvalidOperationException($\"[KyrolusMediator] Could not find Handle(...) on {commandHandlerType.FullName}.\");");
                sb.AppendLine($"                var task = (Task)method.Invoke(commandHandler, new object[] {{ {inputParamName}, cancellationToken }})!;");
                sb.AppendLine("                return task;");
                sb.AppendLine(Indent12CloseBrace);
                return;
            }

            sb.AppendLine("            Type? openGenericHandlerType = null;");
            sb.AppendLine($"            if ({inputParamName} is IKyrolusCommandBase)");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine($"                openGenericHandlerType = typeof(IKyrolusCommandHandler<,>).MakeGenericType({localRequestVarName}, typeof(TResponse));");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine($"            else if ({inputParamName} is IKyrolusQueryBase)");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine($"                openGenericHandlerType = typeof(IKyrolusQueryHandler<,>).MakeGenericType({localRequestVarName}, typeof(TResponse));");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine("            else");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine($"                openGenericHandlerType = typeof(IKyrolusRequestHandler<,>).MakeGenericType({localRequestVarName}, typeof(TResponse));");
            sb.AppendLine(Indent12CloseBrace);
            sb.AppendLine();
            sb.AppendLine("            var openHandler = openGenericHandlerType is null ? null : serviceProvider.GetService(openGenericHandlerType);");
            sb.AppendLine("            if (openHandler is not null)");
            sb.AppendLine(Indent12OpenBrace);
            sb.AppendLine("                var method = openGenericHandlerType!.GetMethod(\"Handle\", new[] { " + localRequestVarName + ", typeof(CancellationToken) });");
            sb.AppendLine("                if (method is null) throw new InvalidOperationException($\"[KyrolusMediator] Could not find Handle(...) on {openGenericHandlerType.FullName}.\");");
            sb.AppendLine($"                var task = (Task<TResponse>)method.Invoke(openHandler, new object[] {{ {inputParamName}, cancellationToken }})!;");
            sb.AppendLine("                return await task;");
            sb.AppendLine(Indent12CloseBrace);
        }

        /// <summary>
        /// Recursively collects namespaces from type symbols for 'using' statements.
        /// </summary>
        private static void CollectNamespaces(ITypeSymbol typeSymbol, ISet<string> namespaces)
        {
            if (typeSymbol is null) return;

            if (typeSymbol is INamedTypeSymbol namedType)
            {
                AddNamespace(namedType, namespaces);
                foreach (var arg in namedType.TypeArguments)
                    CollectNamespaces(arg, namespaces);

                if (namedType.ContainingType is not null)
                    CollectNamespaces(namedType.ContainingType, namespaces);

                return;
            }

            if (typeSymbol is IArrayTypeSymbol arrayType)
            {
                CollectNamespaces(arrayType.ElementType, namespaces);
                return;
            }

            AddNamespace(typeSymbol, namespaces);
        }

        private static void AddNamespace(ITypeSymbol typeSymbol, ISet<string> namespaces)
        {
            if (typeSymbol.ContainingNamespace is not null && !typeSymbol.ContainingNamespace.IsGlobalNamespace)
               namespaces.Add(typeSymbol.ContainingNamespace.ToDisplayString());
        }
    } // End Generator class
} // End namespace
