using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace KyrolusSous.Validation.Generator;

[Generator]
public sealed class KyrolusValidationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
            static (ctx, _) => (INamedTypeSymbol?)ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node))
            .Where(static symbol => symbol is not null);

        var compilationAndCandidates = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(compilationAndCandidates, static (spc, pair) =>
        {
            Emit(spc, pair.Left, pair.Right);
        });
    }

    private static void Emit(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol?> candidates)
    {
        var validatorInterface = compilation.GetTypeByMetadataName("KyrolusSous.Validation.Abstractions.IKyrolusRequestValidator`1");
        if (validatorInterface is null)
        {
            return;
        }

        var profileType = compilation.GetTypeByMetadataName("KyrolusSous.Validation.Abstractions.KyrolusValidationProfile");
        var profilesType = compilation.GetTypeByMetadataName("KyrolusSous.Validation.Abstractions.KyrolusValidationProfiles");
        var emitProfiles = profileType is not null && profilesType is not null;

        var registrations = new HashSet<(string ServiceType, string ImplementationType)>();

        foreach (var candidate in candidates)
        {
            if (candidate is null || candidate.IsAbstract || candidate.TypeParameters.Length > 0)
            {
                continue;
            }

            foreach (var iface in candidate.AllInterfaces)
            {
                if (!SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, validatorInterface))
                {
                    continue;
                }

                var serviceType = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var implType = candidate.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                registrations.Add((serviceType, implType));
            }
        }

        if (registrations.Count == 0 && !emitProfiles)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        if (emitProfiles)
        {
            sb.AppendLine("using KyrolusSous.Validation.Abstractions;");
        }
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("namespace KyrolusSous.Validation.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class KyrolusValidationGeneratedServiceCollectionExtensions");
        sb.AppendLine("{");
        if (registrations.Count > 0)
        {
            sb.AppendLine("    public static IServiceCollection AddKyrolusGeneratedValidators(this IServiceCollection services)");
            sb.AppendLine("    {");

            foreach (var registration in registrations.OrderBy(r => r.ImplementationType))
            {
                sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Scoped(typeof({registration.ServiceType}), typeof({registration.ImplementationType})));");
            }

            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
        }

        if (emitProfiles)
        {
            sb.AppendLine();
            sb.AppendLine("    public static IServiceCollection AddKyrolusGeneratedValidationProfiles(this IServiceCollection services)");
            sb.AppendLine("    {");
            sb.AppendLine("        services.TryAddEnumerable(ServiceDescriptor.Singleton<KyrolusValidationProfile>(KyrolusValidationProfiles.Create));");
            sb.AppendLine("        services.TryAddEnumerable(ServiceDescriptor.Singleton<KyrolusValidationProfile>(KyrolusValidationProfiles.Update));");
            sb.AppendLine("        services.TryAddEnumerable(ServiceDescriptor.Singleton<KyrolusValidationProfile>(KyrolusValidationProfiles.UiHints));");
            sb.AppendLine("        services.TryAddEnumerable(ServiceDescriptor.Singleton<KyrolusValidationProfile>(KyrolusValidationProfiles.BackgroundJobs));");
            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");

        context.AddSource("KyrolusValidationGeneratedServiceCollectionExtensions.g.cs", sb.ToString());
    }
}
