global using System.Net;
global using KyrolusSous.ExceptionHandling.Abstractions.Models;
global using System.Globalization;
global using System.Collections.Concurrent;
global using System.Text.RegularExpressions;
global using KyrolusSous.ExceptionHandling.Abstractions.Exceptions;
global using System.Net.Sockets;
global using System.Text.Json;
global using KyrolusSous.ExceptionHandling.Abstractions.Interfaces;