<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>KyrolusSous.ExceptionHandling.Abstractions</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Localization\KyrolusSous.Localization.Abstractions\KyrolusSous.Localization.Abstractions.csproj" />
  </ItemGroup>

</Project>
