namespace KyrolusSous.CQRS.Abstractions.Audit;

/// <summary>
/// Represents an immutable audit trail entry generated by an auditable CQRS command or request.
/// </summary>
public sealed record KyrolusAuditEntry
{
    /// <summary>
    /// Gets the unique identifier for this audit record.
    /// </summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>
    /// Gets the user ID of the actor who executed the command.
    /// </summary>
    public string? UserId { get; init; }

    /// <summary>
    /// Gets the username or display name of the actor.
    /// </summary>
    public string? UserName { get; init; }
    /// <summary>
    /// Gets the tenant ID associated with the execution context.
    /// </summary>
    public string? TenantId { get; init; }

    /// <summary>
    /// Gets the technical or developer action name (e.g. "CreateOrderCommand" or custom action name).
    /// </summary>
    public required string Action { get; init; }

    /// <summary>
    /// Gets the business action code or localization key (e.g. "Orders.Create" or "Payroll.Disburse").
    /// </summary>
    public string? BusinessAction { get; init; }

    /// <summary>
    /// Gets the localized business action description evaluated at execution time using the active culture (e.g. "صرف الرواتب الشهرية").
    /// </summary>
    public string? LocalizedAction { get; init; }

    /// <summary>
    /// Gets the optional audit category or domain module.
    /// </summary>
    public string? Category { get; init; }

    /// <summary>
    /// Gets the short C# class name of the executed command (e.g. "CreateOrderCommand").
    /// </summary>
    public required string CommandName { get; init; }

    /// <summary>
    /// Gets the full C# type name of the executed command including its namespace (e.g. "MyProject.Orders.Commands.CreateOrderCommand").
    /// </summary>
    public required string CommandFullName { get; init; }

    /// <summary>
    /// Gets the serialized or captured request payload, if enabled.
    /// </summary>
    public object? Payload { get; init; }

    /// <summary>
    /// Gets the UTC timestamp when the request started execution.
    /// </summary>
    public DateTimeOffset TimestampUtc { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Gets the execution duration in milliseconds.
    /// </summary>
    public long DurationMs { get; init; }

    /// <summary>
    /// Gets a value indicating whether the request completed successfully.
    /// </summary>
    public bool IsSuccess { get; init; }

    /// <summary>
    /// Gets the error message if the execution failed.
    /// </summary>
    public string? ErrorMessage { get; init; }
}
