<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Core implementation for Kyrolus dynamic feature management, tenant gating, and percentage rollouts.</Description>
    <PackageTags>$(PackageTags);featuremanagement;featureflags;toggles;core</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KyrolusSous.FeatureManagement.Abstractions\KyrolusSous.FeatureManagement.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
