#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash scripts/library-quality.sh [options]

Options:
  -t, --target <path>           Target test project/solution for coverage run.
                                Default: coverage.target from quality-gates.json.
      --with-sqlite             Run SQLite integration tests after coverage gates.
      --with-sqlserver          Run SQL Server integration tests after coverage gates.
      --all-suites              Run every suite marked ci:true in quality-gates.json.
      --skip-coverage           Skip coverage run/gates (only provider test runs).
      --min-line <num>          Override overall min line coverage percent.
      --min-branch <num>        Override overall min branch coverage percent.
      --config <path>           Quality gates config (default: quality-gates.json).
      --python <exe>            Python executable (default: auto python3/python).
  -h, --help                    Show this help.

Notes:
  - This script depends on scripts/dotnet-coverage.sh output at the path in
    coverage.report of quality-gates.json.
  - Thresholds live ONLY in quality-gates.json. Do not hardcode them here or in
    docs/QUALITY_STRATEGY.md - that file is generated by scripts/update-docs.py.
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SQLITE_PROJECT="Tests/KyrolusSous.Repositories.EF.Runtime/IntegrationTests/IntegrationTests.SQLlite/KyrolusSous.Repositories.EF.Runtime.IntegrationTests.SQLlite.csproj"
SQLSERVER_PROJECT="Tests/KyrolusSous.Repositories.EF.Runtime/IntegrationTests/IntegrationTests.SQLSever/KyrolusSous.Repositories.EF.Runtime.IntegrationTests.SQLSever.csproj"

CONFIG_PATH="$REPO_ROOT/quality-gates.json"
TARGET=""
WITH_SQLITE="false"
WITH_SQLSERVER="false"
ALL_SUITES="false"
SKIP_COVERAGE="false"
MIN_LINE=""
MIN_BRANCH=""
PYTHON_EXE=""
PYTHON_CMD=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -t|--target)
      [[ $# -ge 2 ]] || { echo "Missing value for $1"; exit 1; }
      TARGET="$2"
      shift 2
      ;;
    --with-sqlite)
      WITH_SQLITE="true"
      shift
      ;;
    --with-sqlserver)
      WITH_SQLSERVER="true"
      shift
      ;;
    --all-suites)
      ALL_SUITES="true"
      shift
      ;;
    --config)
      [[ $# -ge 2 ]] || { echo "Missing value for $1"; exit 1; }
      CONFIG_PATH="$2"
      shift 2
      ;;
    --skip-coverage)
      SKIP_COVERAGE="true"
      shift
      ;;
    --min-line)
      [[ $# -ge 2 ]] || { echo "Missing value for $1"; exit 1; }
      MIN_LINE="$2"
      shift 2
      ;;
    --min-branch)
      [[ $# -ge 2 ]] || { echo "Missing value for $1"; exit 1; }
      MIN_BRANCH="$2"
      shift 2
      ;;
    --python)
      [[ $# -ge 2 ]] || { echo "Missing value for $1"; exit 1; }
      PYTHON_EXE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ -n "$PYTHON_EXE" ]]; then
  if ! "$PYTHON_EXE" -V >/dev/null 2>&1; then
    echo "ERROR: Provided python executable is not runnable: $PYTHON_EXE"
    exit 1
  fi
  PYTHON_CMD=("$PYTHON_EXE")
else
  if command -v python3 >/dev/null 2>&1 && python3 -V >/dev/null 2>&1; then
    PYTHON_CMD=(python3)
  elif command -v python >/dev/null 2>&1 && python -V >/dev/null 2>&1; then
    PYTHON_CMD=(python)
  elif command -v py >/dev/null 2>&1 && py -3 -V >/dev/null 2>&1; then
    PYTHON_CMD=(py -3)
  else
    echo "ERROR: Python is required (python3/python/py not found)."
    exit 1
  fi
fi

if [[ ! -f "$CONFIG_PATH" ]]; then
  echo "ERROR: Quality gates config not found: $CONFIG_PATH"
  exit 1
fi

# Pull the derived paths out of the config so nothing here duplicates them.
config_value() {
  "${PYTHON_CMD[@]}" -c "
import json, sys
with open(sys.argv[1], encoding='utf-8') as handle:
    config = json.load(handle)
print(config.get('coverage', {}).get(sys.argv[2], ''))
" "$CONFIG_PATH" "$1"
}

config_ci_suites() {
  "${PYTHON_CMD[@]}" -c "
import json, sys
with open(sys.argv[1], encoding='utf-8') as handle:
    config = json.load(handle)
for suite in config.get('testSuites', []):
    if suite.get('ci'):
        print(suite['project'])
" "$CONFIG_PATH"
}

REPORT_PATH="$REPO_ROOT/$(config_value report)"
if [[ -z "$TARGET" ]]; then
  TARGET="$(config_value target)"
fi

if [[ -z "$TARGET" ]]; then
  echo "ERROR: No coverage target in config and none passed via --target."
  exit 1
fi

run_tests() {
  local project="$1"
  local label="$2"
  if [[ ! -f "$REPO_ROOT/$project" ]]; then
    echo "WARN: $label project not found at '$project'. Skipping."
    return 0
  fi

  echo "Running $label tests..."
  dotnet test "$REPO_ROOT/$project" -c Debug
}

if [[ "$SKIP_COVERAGE" != "true" ]]; then
  echo "Running coverage + report for target: $TARGET"
  bash "$SCRIPT_DIR/dotnet-coverage.sh" -t "$TARGET"

  if [[ ! -f "$REPORT_PATH" ]]; then
    echo "ERROR: Coverage report not found: $REPORT_PATH"
    exit 1
  fi

  echo "Applying coverage quality gates from $CONFIG_PATH..."
  gate_args=(--config "$CONFIG_PATH" --report "$REPORT_PATH")
  [[ -n "$MIN_LINE" ]] && gate_args+=(--min-line "$MIN_LINE")
  [[ -n "$MIN_BRANCH" ]] && gate_args+=(--min-branch "$MIN_BRANCH")

  "${PYTHON_CMD[@]}" "$SCRIPT_DIR/coverage-gate.py" "${gate_args[@]}"
fi

if [[ "$ALL_SUITES" == "true" ]]; then
  while IFS= read -r suite; do
    [[ -z "$suite" ]] && continue
    # The coverage run already executed this one.
    [[ "$suite" == "$TARGET" && "$SKIP_COVERAGE" != "true" ]] && continue
    run_tests "$suite" "$(basename "$suite" .csproj)"
  done < <(config_ci_suites)
else
  if [[ "$WITH_SQLITE" == "true" ]]; then
    run_tests "$SQLITE_PROJECT" "SQLite"
  fi

  if [[ "$WITH_SQLSERVER" == "true" ]]; then
    run_tests "$SQLSERVER_PROJECT" "SQL Server"
  fi
fi

echo "Library quality checks completed successfully."
