<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Src\Storage\KyrolusSous.Storage.Abstractions\KyrolusSous.Storage.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\..\Src\Storage\KyrolusSous.Storage.FileSystem\KyrolusSous.Storage.FileSystem.csproj" />
    <ProjectReference Include="..\..\..\..\Src\Compression\KyrolusSous.Compression.Gzip\KyrolusSous.Compression.Gzip.csproj" />
  </ItemGroup>

</Project>
