global using KyrolusSous.CQRS.Abstractions.Interfaces;
global using KyrolusSous.Repositories.EF.Abstractions.Interfaces;
global using System.Linq.Expressions;
global using System.Reflection;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using KyrolusSous.Mediator.Abstractions.Interfaces;
global using Microsoft.EntityFrameworkCore;
global using KyrolusSous.CQRS.EF;
